// Derived from:
//   http://www.gamefaqs.com/ps2/945498-shin-megami-tensei-persona-4/faqs/54981
//   http://www.gamefaqs.com/ps2/945498-shin-megami-tensei-persona-4/faqs/54981

const personae = [
    {'arcana': 'Fool',        'level':  1, 'name': 'Izanagi',           },
    {'arcana': 'Fool',        'level':  7, 'name': 'Yomotsu-Shikome',   },
    {'arcana': 'Fool',        'level': 13, 'name': 'Obariyon',          },
    {'arcana': 'Fool',        'level': 21, 'name': 'Legion',            },
    {'arcana': 'Fool',        'level': 31, 'name': 'Ose',               },
    {'arcana': 'Fool',        'level': 38, 'name': 'Black Frost',       'special': true },
    {'arcana': 'Fool',        'level': 46, 'name': 'Decarabia',         },
    {'arcana': 'Fool',        'level': 56, 'name': 'Shiki-Ouji',        },
    {'arcana': 'Fool',        'level': 64, 'name': 'Loki',              'max': true, },
    {'arcana': 'Magician',    'level':  2, 'name': 'Pixie',             },
    {'arcana': 'Magician',    'level':  8, 'name': 'Orobas',            },
    {'arcana': 'Magician',    'level': 16, 'name': 'Jack Frost',        },
    {'arcana': 'Magician',    'level': 25, 'name': 'Hua Po',            },
    {'arcana': 'Magician',    'level': 32, 'name': 'Pyro Jack',         },
    {'arcana': 'Magician',    'level': 39, 'name': 'Dis',               },
    {'arcana': 'Magician',    'level': 47, 'name': 'Rangda',            },
    {'arcana': 'Magician',    'level': 62, 'name': 'Jinn',              },
    {'arcana': 'Magician',    'level': 69, 'name': 'Surt',              },
    {'arcana': 'Magician',    'level': 78, 'name': 'Mada',              'max': true, },
    {'arcana': 'Priestess',   'level': 11, 'name': 'Saki Mitama',       },
    {'arcana': 'Priestess',   'level': 17, 'name': 'Sarasvati',         },
    {'arcana': 'Priestess',   'level': 22, 'name': 'High Pixie',        },
    {'arcana': 'Priestess',   'level': 29, 'name': 'Ganga',             },
    {'arcana': 'Priestess',   'level': 37, 'name': 'Parvati',           },
    {'arcana': 'Priestess',   'level': 48, 'name': 'Kikuri-Hime',       },
    {'arcana': 'Priestess',   'level': 59, 'name': 'Hariti',            },
    {'arcana': 'Priestess',   'level': 70, 'name': 'Tzitzimitl',        },
    {'arcana': 'Priestess',   'level': 79, 'name': 'Scathach',          'max': true, },
    {'arcana': 'Empress',     'level':  9, 'name': 'Senri',             },
    {'arcana': 'Empress',     'level': 18, 'name': 'Yaksini',           },
    {'arcana': 'Empress',     'level': 26, 'name': 'Titania',           },
    {'arcana': 'Empress',     'level': 34, 'name': 'Gorgon',            },
    {'arcana': 'Empress',     'level': 44, 'name': 'Gabriel',           },
    {'arcana': 'Empress',     'level': 52, 'name': 'Skadi',             },
    {'arcana': 'Empress',     'level': 60, 'name': 'Mother Harlot',     },
    {'arcana': 'Empress',     'level': 70, 'name': 'Alilat',            },
    {'arcana': 'Empress',     'level': 79, 'name': 'Isis',              'max': true, },
    {'arcana': 'Emperor',     'level': 12, 'name': 'Oberon',            },
    {'arcana': 'Emperor',     'level': 22, 'name': 'King Frost',        },
    {'arcana': 'Emperor',     'level': 34, 'name': 'Setanta',           },
    {'arcana': 'Emperor',     'level': 41, 'name': 'Oukuninushi',       },
    {'arcana': 'Emperor',     'level': 45, 'name': 'Thoth',             },
    {'arcana': 'Emperor',     'level': 51, 'name': 'Pabilsag',          },
    {'arcana': 'Emperor',     'level': 65, 'name': 'Barong',            },
    {'arcana': 'Emperor',     'level': 74, 'name': 'Odin',              'max': true, },
    {'arcana': 'Heirophant',  'level':  7, 'name': 'Omoikane',          },
    {'arcana': 'Heirophant',  'level': 15, 'name': 'Anzu',              },
    {'arcana': 'Heirophant',  'level': 21, 'name': 'Shiisaa',           },
    {'arcana': 'Heirophant',  'level': 29, 'name': 'Unicorn',           },
    {'arcana': 'Heirophant',  'level': 36, 'name': 'Flauros',           },
    {'arcana': 'Heirophant',  'level': 45, 'name': 'Hokuto Seikun',     },
    {'arcana': 'Heirophant',  'level': 52, 'name': 'Cerberus',          },
    {'arcana': 'Heirophant',  'level': 60, 'name': 'Daisoujou',         },
    {'arcana': 'Heirophant',  'level': 70, 'name': 'Hachiman',          },
    {'arcana': 'Heirophant',  'level': 76, 'name': 'Kohryu',            'max': true, 'special': true },
    {'arcana': 'Lovers',      'level': 25, 'name': 'Queen Mab',         },
    {'arcana': 'Lovers',      'level': 33, 'name': 'Undine',            },
    {'arcana': 'Lovers',      'level': 42, 'name': 'Leanan Sidhe',      },
    {'arcana': 'Lovers',      'level': 53, 'name': 'Raphael',           },
    {'arcana': 'Lovers',      'level': 64, 'name': 'Cybele',            },
    {'arcana': 'Lovers',      'level': 71, 'name': 'Ishtar',            'max': true, },
    {'arcana': 'Chariot',     'level':  2, 'name': 'Slime',             },
    {'arcana': 'Chariot',     'level':  6, 'name': 'Nata Taishi',       },
    {'arcana': 'Chariot',     'level': 12, 'name': 'Eligor',            },
    {'arcana': 'Chariot',     'level': 18, 'name': 'Ara Mitama',        },
    {'arcana': 'Chariot',     'level': 25, 'name': 'Ares',              },
    {'arcana': 'Chariot',     'level': 43, 'name': 'Triglav',           },
    {'arcana': 'Chariot',     'level': 54, 'name': 'Kin-ki',            },
    {'arcana': 'Chariot',     'level': 65, 'name': 'Thor',              },
    {'arcana': 'Chariot',     'level': 72, 'name': 'Atavaka',           },
    {'arcana': 'Chariot',     'level': 80, 'name': 'Futsunushi',        'max': true, 'special': true },
    {'arcana': 'Justice',     'level':  4, 'name': 'Angel',             },
    {'arcana': 'Justice',     'level': 11, 'name': 'Archangel',         },
    {'arcana': 'Justice',     'level': 19, 'name': 'Principality',      },
    {'arcana': 'Justice',     'level': 27, 'name': 'Power',             },
    {'arcana': 'Justice',     'level': 33, 'name': 'Virtue',            },
    {'arcana': 'Justice',     'level': 38, 'name': 'Dominion',          },
    {'arcana': 'Justice',     'level': 49, 'name': 'Throne',            },
    {'arcana': 'Justice',     'level': 58, 'name': 'Uriel',             },
    {'arcana': 'Justice',     'level': 66, 'name': 'Melchizedek',       },
    {'arcana': 'Justice',     'level': 74, 'name': 'Sraosha',           'max': true, },
    {'arcana': 'Hermit',      'level':  6, 'name': 'Forneus',           },
    {'arcana': 'Hermit',      'level': 17, 'name': 'Ippon-Datara',      },
    {'arcana': 'Hermit',      'level': 26, 'name': 'Lamia',             },
    {'arcana': 'Hermit',      'level': 33, 'name': 'Mothman',           },
    {'arcana': 'Hermit',      'level': 41, 'name': 'Hitokoto-Nushi',    },
    {'arcana': 'Hermit',      'level': 48, 'name': 'Kurama Tengu',      },
    {'arcana': 'Hermit',      'level': 55, 'name': 'Niddhoggr',         },
    {'arcana': 'Hermit',      'level': 63, 'name': 'Nebiros',           },
    {'arcana': 'Hermit',      'level': 73, 'name': 'Arahabaki',         },
    {'arcana': 'Hermit',      'level': 82, 'name': 'Ongyo-ki',          'max': true, 'special': true },
    {'arcana': 'Fortune',     'level': 35, 'name': 'Fortuna',           },
    {'arcana': 'Fortune',     'level': 44, 'name': 'Clotho',            },
    {'arcana': 'Fortune',     'level': 51, 'name': 'Lachesis',          },
    {'arcana': 'Fortune',     'level': 58, 'name': 'Ananta',            },
    {'arcana': 'Fortune',     'level': 65, 'name': 'Atropos',           },
    {'arcana': 'Fortune',     'level': 72, 'name': 'Norn',              'max': true, 'special': true },
    {'arcana': 'Strength',    'level':  5, 'name': 'Sandman',           },
    {'arcana': 'Strength',    'level':  8, 'name': 'Valkyrie',          },
    {'arcana': 'Strength',    'level': 14, 'name': 'Titan',             },
    {'arcana': 'Strength',    'level': 23, 'name': 'Rakshasa',          },
    {'arcana': 'Strength',    'level': 28, 'name': 'Kusi Mitama',       },
    {'arcana': 'Strength',    'level': 30, 'name': 'Oni',               },
    {'arcana': 'Strength',    'level': 42, 'name': 'Hanuman',           },
    {'arcana': 'Strength',    'level': 50, 'name': 'Kali',              },
    {'arcana': 'Strength',    'level': 63, 'name': 'Siegfried',         },
    {'arcana': 'Strength',    'level': 90, 'name': 'Zaou-Gongen',       'max': true, },
    {'arcana': 'Hanged Man',  'level': 15, 'name': 'Berith',            },
    {'arcana': 'Hanged Man',  'level': 22, 'name': 'Yomotsu-Ikusa',     },
    {'arcana': 'Hanged Man',  'level': 27, 'name': 'Makami',            },
    {'arcana': 'Hanged Man',  'level': 39, 'name': 'Orthrus',           },
    {'arcana': 'Hanged Man',  'level': 49, 'name': 'Yatsufusa',         'special': true },
    {'arcana': 'Hanged Man',  'level': 56, 'name': 'Taowu',             },
    {'arcana': 'Hanged Man',  'level': 66, 'name': 'Hell Biker',        },
    {'arcana': 'Hanged Man',  'level': 71, 'name': 'Vasuki',            },
    {'arcana': 'Hanged Man',  'level': 82, 'name': 'Attis',             'max': true, },
    {'arcana': 'Death',       'level':  9, 'name': 'Ghoul',             },
    {'arcana': 'Death',       'level': 14, 'name': 'Mokoi',             },
    {'arcana': 'Death',       'level': 24, 'name': 'Matador',           },
    {'arcana': 'Death',       'level': 36, 'name': 'Samael',            },
    {'arcana': 'Death',       'level': 46, 'name': 'Mot',               },
    {'arcana': 'Death',       'level': 58, 'name': 'White Rider',       },
    {'arcana': 'Death',       'level': 72, 'name': 'Alice',             'special': true },
    {'arcana': 'Death',       'level': 78, 'name': 'Mahakala',          'max': true, 'special': true },
    {'arcana': 'Temperance',  'level':  4, 'name': 'Apsaras',           },
    {'arcana': 'Temperance',  'level': 11, 'name': 'Sylph',             },
    {'arcana': 'Temperance',  'level': 16, 'name': 'Xiezhai',           },
    {'arcana': 'Temperance',  'level': 23, 'name': 'Nigi Mitama',       },
    {'arcana': 'Temperance',  'level': 31, 'name': 'Mithra',            },
    {'arcana': 'Temperance',  'level': 40, 'name': 'Genbu',             },
    {'arcana': 'Temperance',  'level': 47, 'name': 'Seiryu',            },
    {'arcana': 'Temperance',  'level': 54, 'name': 'Suzaku',            },
    {'arcana': 'Temperance',  'level': 62, 'name': 'Byakko',            },
    {'arcana': 'Temperance',  'level': 69, 'name': 'Yurlungur',         },
    {'arcana': 'Temperance',  'level': 73, 'name': 'Vishnu',            'max': true, },
    {'arcana': 'Devil',       'level':  3, 'name': 'Ukobach',           },
    {'arcana': 'Devil',       'level': 10, 'name': 'Lilim',             },
    {'arcana': 'Devil',       'level': 19, 'name': 'Vetala',            },
    {'arcana': 'Devil',       'level': 28, 'name': 'Incubus',           },
    {'arcana': 'Devil',       'level': 37, 'name': 'Pazuzu',            },
    {'arcana': 'Devil',       'level': 44, 'name': 'Succubus',          },
    {'arcana': 'Devil',       'level': 53, 'name': 'Lilith',            },
    {'arcana': 'Devil',       'level': 61, 'name': 'Belphegor',         },
    {'arcana': 'Devil',       'level': 68, 'name': 'Belial',            },
    {'arcana': 'Devil',       'level': 81, 'name': 'Beelzebub',         'max': true, 'special': true },
    {'arcana': 'Tower',       'level': 35, 'name': 'Taotie',            },
    {'arcana': 'Tower',       'level': 46, 'name': 'Cu Chulainn',       },
    {'arcana': 'Tower',       'level': 55, 'name': 'Abaddon',           },
    {'arcana': 'Tower',       'level': 62, 'name': 'Mara',              },
    {'arcana': 'Tower',       'level': 69, 'name': 'Masakado',          },
    {'arcana': 'Tower',       'level': 75, 'name': 'Yoshitsune',        'special': true },
    {'arcana': 'Tower',       'level': 80, 'name': 'Shiva',             'max': true, 'special': true },
    {'arcana': 'Star',        'level': 24, 'name': 'Kaiwan',            },
    {'arcana': 'Star',        'level': 32, 'name': 'Neko Shogun',       'special': true },
    {'arcana': 'Star',        'level': 43, 'name': 'Fuu-ki',            },
    {'arcana': 'Star',        'level': 50, 'name': 'Ganesha',           },
    {'arcana': 'Star',        'level': 57, 'name': 'Garuda',            },
    {'arcana': 'Star',        'level': 67, 'name': 'Kartikeya',         },
    {'arcana': 'Star',        'level': 75, 'name': 'Saturnus',          },
    {'arcana': 'Star',        'level': 87, 'name': 'Helel',             'max': true, },
    {'arcana': 'Moon',        'level': 20, 'name': 'Andra',             },
    {'arcana': 'Moon',        'level': 27, 'name': 'Nozuchi',           },
    {'arcana': 'Moon',        'level': 34, 'name': 'Yamata-no-Orochi',  },
    {'arcana': 'Moon',        'level': 41, 'name': 'Alraune',           },
    {'arcana': 'Moon',        'level': 48, 'name': 'Girimehkala',       },
    {'arcana': 'Moon',        'level': 57, 'name': 'Sui-ki',            },
    {'arcana': 'Moon',        'level': 68, 'name': 'Seth',              },
    {'arcana': 'Moon',        'level': 77, 'name': 'Baal Zebul',        },
    {'arcana': 'Moon',        'level': 84, 'name': 'Sandalphon',        'max': true, },
    {'arcana': 'Sun',         'level': 10, 'name': 'Cu Sith',           },
    {'arcana': 'Sun',         'level': 20, 'name': 'Phoenix',           },
    {'arcana': 'Sun',         'level': 31, 'name': 'Gdon',              },
    {'arcana': 'Sun',         'level': 40, 'name': 'Yatagarasu',        },
    {'arcana': 'Sun',         'level': 47, 'name': 'Narasimha',         },
    {'arcana': 'Sun',         'level': 53, 'name': 'Tam Lin',           'special': true },
    {'arcana': 'Sun',         'level': 61, 'name': 'Jatayu',            },
    {'arcana': 'Sun',         'level': 68, 'name': 'Horus',             },
    {'arcana': 'Sun',         'level': 77, 'name': 'Suparna',           },
    {'arcana': 'Sun',         'level': 86, 'name': 'Asura',             'max': true, },
    {'arcana': 'Judgement',   'level': 59, 'name': 'Anubis',            },
    {'arcana': 'Judgement',   'level': 67, 'name': 'Trumpeter',         'special': true },
    {'arcana': 'Judgement',   'level': 72, 'name': 'Michael',           },
    {'arcana': 'Judgement',   'level': 76, 'name': 'Satan',             },
    {'arcana': 'Judgement',   'level': 83, 'name': 'Metatron',          },
    {'arcana': 'Judgement',   'level': 90, 'name': 'Ardha',             'max': true, 'special': true },
    {'arcana': 'Judgement',   'level': 93, 'name': 'Lucifer',           'max': true, 'special': true },
    {'arcana': 'World',       'level': 91, 'name': 'Izanagi-no-Okami',  'max': true, 'special': true },
    ];

const arcana2Combos = [
    {'source': ['Fool',       'Fool',       ], 'result': 'Fool'        },
    {'source': ['Fool',       'Magician',   ], 'result': 'Temperance'  },
    {'source': ['Fool',       'Priestess',  ], 'result': 'Death'       },
    {'source': ['Fool',       'Empress',    ], 'result': 'Moon'        },
    {'source': ['Fool',       'Emperor',    ], 'result': 'Death'       },
    {'source': ['Fool',       'Heirophant', ], 'result': 'Chariot'     },
    {'source': ['Fool',       'Lovers',     ], 'result': 'Empress'     },
    {'source': ['Fool',       'Chariot',    ], 'result': 'Sun'         },
    {'source': ['Fool',       'Justice',    ], 'result': 'Magician'    },
    {'source': ['Fool',       'Hermit',     ], 'result': 'Strength'    },
    {'source': ['Fool',       'Fortune',    ], 'result': 'Magician'    },
    {'source': ['Fool',       'Strength',   ], 'result': 'Magician'    },
    {'source': ['Fool',       'Hanged Man', ], 'result': 'Strength'    },
    {'source': ['Fool',       'Death',      ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Temperance', ], 'result': 'Heirophant'  },
    {'source': ['Fool',       'Devil',      ], 'result': 'Temperance'  },
    {'source': ['Fool',       'Tower',      ], 'result': 'Star'        },
    {'source': ['Fool',       'Star',       ], 'result': 'Empress'     },
    {'source': ['Fool',       'Moon',       ], 'result': 'Emperor'     },
    {'source': ['Fool',       'Sun',        ], 'result': 'Devil'       },
    {'source': ['Fool',       'Judgement',  ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Magician',   ], 'result': 'Magician'    },
    {'source': ['Magician',   'Priestess',  ], 'result': 'Moon'        },
    {'source': ['Magician',   'Empress',    ], 'result': 'Justice'     },
    {'source': ['Magician',   'Emperor',    ], 'result': 'Strength'    },
    {'source': ['Magician',   'Heirophant', ], 'result': 'Devil'       },
    {'source': ['Magician',   'Lovers',     ], 'result': 'Death'       },
    {'source': ['Magician',   'Chariot',    ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Justice',    ], 'result': 'Strength'    },
    {'source': ['Magician',   'Hermit',     ], 'result': 'Empress'     },
    {'source': ['Magician',   'Fortune',    ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Strength',   ], 'result': 'Justice'     },
    {'source': ['Magician',   'Hanged Man', ], 'result': 'Sun'         },
    {'source': ['Magician',   'Death',      ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Temperance', ], 'result': 'Strength'    },
    {'source': ['Magician',   'Devil',      ], 'result': 'Sun'         },
    {'source': ['Magician',   'Tower',      ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Moon',       ], 'result': 'Star'        },
    {'source': ['Magician',   'Sun',        ], 'result': 'Chariot'     },
    {'source': ['Magician',   'Judgement',  ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Priestess',  ], 'result': 'Priestess'   },
    {'source': ['Priestess',  'Empress',    ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Emperor',    ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Heirophant', ], 'result': 'Sun'         },
    {'source': ['Priestess',  'Lovers',     ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Chariot',    ], 'result': 'Heirophant'  },
    {'source': ['Priestess',  'Justice',    ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Hermit',     ], 'result': 'Death'       },
    {'source': ['Priestess',  'Fortune',    ], 'result': 'Hanged Man'  },
    {'source': ['Priestess',  'Strength',   ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Hanged Man', ], 'result': 'Moon'        },
    {'source': ['Priestess',  'Death',      ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Temperance', ], 'result': 'Heirophant'  },
    {'source': ['Priestess',  'Devil',      ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Tower',      ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Star',       ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Moon',       ], 'result': 'Star'        },
    {'source': ['Priestess',  'Sun',        ], 'result': 'Devil'       },
    {'source': ['Priestess',  'Judgement',  ], 'result': 'Sun'         },
    {'source': ['Empress',    'Empress',    ], 'result': 'Empress'     },
    {'source': ['Empress',    'Emperor',    ], 'result': 'Moon'        },
    {'source': ['Empress',    'Heirophant', ], 'result': 'Death'       },
    {'source': ['Empress',    'Lovers',     ], 'result': 'Justice'     },
    {'source': ['Empress',    'Chariot',    ], 'result': 'Justice'     },
    {'source': ['Empress',    'Justice',    ], 'result': 'Magician'    },
    {'source': ['Empress',    'Hermit',     ], 'result': 'Magician'    },
    {'source': ['Empress',    'Fortune',    ], 'result': 'Star'        },
    {'source': ['Empress',    'Strength',   ], 'result': 'Heirophant'  },
    {'source': ['Empress',    'Hanged Man', ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Death',      ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Temperance', ], 'result': 'Devil'       },
    {'source': ['Empress',    'Devil',      ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Tower',      ], 'result': 'Hermit'      },
    {'source': ['Empress',    'Star',       ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Moon',       ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Sun',        ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Judgement',  ], 'result': 'Priestess'   },
    {'source': ['Emperor',    'Emperor',    ], 'result': 'Emperor'     },
    {'source': ['Emperor',    'Heirophant', ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Lovers',     ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Chariot',    ], 'result': 'Temperance'  },
    {'source': ['Emperor',    'Justice',    ], 'result': 'Devil'       },
    {'source': ['Emperor',    'Hermit',     ], 'result': 'Priestess'   },
    {'source': ['Emperor',    'Fortune',    ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Strength',   ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Hanged Man', ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Death',      ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Temperance', ], 'result': 'Sun'         },
    {'source': ['Emperor',    'Devil',      ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Tower',      ], 'result': 'Star'        },
    {'source': ['Emperor',    'Star',       ], 'result': 'Death'       },
    {'source': ['Emperor',    'Moon',       ], 'result': 'Magician'    },
    {'source': ['Emperor',    'Sun',        ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Judgement',  ], 'result': 'Lovers'      },
    {'source': ['Heirophant', 'Heirophant', ], 'result': 'Heirophant'  },
    {'source': ['Heirophant', 'Lovers',     ], 'result': 'Death'       },
    {'source': ['Heirophant', 'Chariot',    ], 'result': 'Sun'         },
    {'source': ['Heirophant', 'Justice',    ], 'result': 'Temperance'  },
    {'source': ['Heirophant', 'Hermit',     ], 'result': 'Justice'     },
    {'source': ['Heirophant', 'Fortune',    ], 'result': 'Priestess'   },
    {'source': ['Heirophant', 'Strength',   ], 'result': 'Sun'         },
    {'source': ['Heirophant', 'Hanged Man', ], 'result': 'Death'       },
    {'source': ['Heirophant', 'Death',      ], 'result': 'Devil'       },
    {'source': ['Heirophant', 'Temperance', ], 'result': 'Magician'    },
    {'source': ['Heirophant', 'Devil',      ], 'result': 'Emperor'     },
    {'source': ['Heirophant', 'Tower',      ], 'result': 'Hanged Man'  },
    {'source': ['Heirophant', 'Star',       ], 'result': 'Moon'        },
    {'source': ['Heirophant', 'Moon',       ], 'result': 'Empress'     },
    {'source': ['Heirophant', 'Sun',        ], 'result': 'Strength'    },
    {'source': ['Heirophant', 'Judgement',  ], 'result': 'Chariot'     },
    {'source': ['Lovers',     'Lovers',     ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Chariot',    ], 'result': 'Heirophant'  },
    {'source': ['Lovers',     'Justice',    ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Hermit',     ], 'result': 'Magician'    },
    {'source': ['Lovers',     'Fortune',    ], 'result': 'Star'        },
    {'source': ['Lovers',     'Strength',   ], 'result': 'Emperor'     },
    {'source': ['Lovers',     'Hanged Man', ], 'result': 'Moon'        },
    {'source': ['Lovers',     'Death',      ], 'result': 'Star'        },
    {'source': ['Lovers',     'Temperance', ], 'result': 'Heirophant'  },
    {'source': ['Lovers',     'Devil',      ], 'result': 'Heirophant'  },
    {'source': ['Lovers',     'Tower',      ], 'result': 'Star'        },
    {'source': ['Lovers',     'Star',       ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Moon',       ], 'result': 'Hanged Man'  },
    {'source': ['Lovers',     'Sun',        ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Judgement',  ], 'result': 'Strength'    },
    {'source': ['Chariot',    'Chariot',    ], 'result': 'Chariot'     },
    {'source': ['Chariot',    'Justice',    ], 'result': 'Temperance'  },
    {'source': ['Chariot',    'Hermit',     ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Fortune',    ], 'result': 'Devil'       },
    {'source': ['Chariot',    'Strength',   ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Hanged Man', ], 'result': 'Death'       },
    {'source': ['Chariot',    'Death',      ], 'result': 'Hermit'      },
    {'source': ['Chariot',    'Temperance', ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Devil',      ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Tower',      ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Star',       ], 'result': 'Heirophant'  },
    {'source': ['Chariot',    'Moon',       ], 'result': 'Sun'         },
    {'source': ['Chariot',    'Sun',        ], 'result': 'Strength'    },
    {'source': ['Chariot',    'Judgement',  ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Justice',    ], 'result': 'Justice'     },
    {'source': ['Justice',    'Hermit',     ], 'result': 'Strength'    },
    {'source': ['Justice',    'Fortune',    ], 'result': 'Lovers'      },
    {'source': ['Justice',    'Strength',   ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Hanged Man', ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Death',      ], 'result': 'Strength'    },
    {'source': ['Justice',    'Temperance', ], 'result': 'Hermit'      },
    {'source': ['Justice',    'Devil',      ], 'result': 'Magician'    },
    {'source': ['Justice',    'Tower',      ], 'result': 'Lovers'      },
    {'source': ['Justice',    'Star',       ], 'result': 'Moon'        },
    {'source': ['Justice',    'Moon',       ], 'result': 'Strength'    },
    {'source': ['Justice',    'Sun',        ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Judgement',  ], 'result': 'Lovers'      },
    {'source': ['Hermit',     'Hermit',     ], 'result': 'Hermit'      },
    {'source': ['Hermit',     'Fortune',    ], 'result': 'Empress'     },
    {'source': ['Hermit',     'Strength',   ], 'result': 'Heirophant'  },
    {'source': ['Hermit',     'Hanged Man', ], 'result': 'Moon'        },
    {'source': ['Hermit',     'Death',      ], 'result': 'Sun'         },
    {'source': ['Hermit',     'Temperance', ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Devil',      ], 'result': 'Justice'     },
    {'source': ['Hermit',     'Tower',      ], 'result': 'Death'       },
    {'source': ['Hermit',     'Star',       ], 'result': 'Justice'     },
    {'source': ['Hermit',     'Moon',       ], 'result': 'Empress'     },
    {'source': ['Hermit',     'Sun',        ], 'result': 'Temperance'  },
    {'source': ['Hermit',     'Judgement',  ], 'result': 'Star'        },
    {'source': ['Fortune',    'Fortune',    ], 'result': 'Fortune'     },
    {'source': ['Fortune',    'Strength',   ], 'result': 'Star'        },
    {'source': ['Fortune',    'Hanged Man', ], 'result': 'Death'       },
    {'source': ['Fortune',    'Death',      ], 'result': 'Hermit'      },
    {'source': ['Fortune',    'Temperance', ], 'result': 'Devil'       },
    {'source': ['Fortune',    'Devil',      ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Tower',      ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Star',       ], 'result': 'Star'        },
    {'source': ['Fortune',    'Moon',       ], 'result': 'Lovers'      },
    {'source': ['Fortune',    'Sun',        ], 'result': 'Priestess'   },
    {'source': ['Fortune',    'Judgement',  ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Strength',   ], 'result': 'Strength'    },
    {'source': ['Strength',   'Hanged Man', ], 'result': 'Heirophant'  },
    {'source': ['Strength',   'Death',      ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Temperance', ], 'result': 'Sun'         },
    {'source': ['Strength',   'Devil',      ], 'result': 'Hermit'      },
    {'source': ['Strength',   'Tower',      ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Star',       ], 'result': 'Emperor'     },
    {'source': ['Strength',   'Moon',       ], 'result': 'Justice'     },
    {'source': ['Strength',   'Sun',        ], 'result': 'Temperance'  },
    {'source': ['Hanged Man', 'Hanged Man', ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Death',      ], 'result': 'Priestess'   },
    {'source': ['Hanged Man', 'Temperance', ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Devil',      ], 'result': 'Justice'     },
    {'source': ['Hanged Man', 'Tower',      ], 'result': 'Hermit'      },
    {'source': ['Hanged Man', 'Star',       ], 'result': 'Empress'     },
    {'source': ['Hanged Man', 'Moon',       ], 'result': 'Priestess'   },
    {'source': ['Hanged Man', 'Sun',        ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Judgement',  ], 'result': 'Empress'     },
    {'source': ['Death',      'Death',      ], 'result': 'Death'       },
    {'source': ['Death',      'Temperance', ], 'result': 'Chariot'     },
    {'source': ['Death',      'Devil',      ], 'result': 'Star'        },
    {'source': ['Death',      'Tower',      ], 'result': 'Lovers'      },
    {'source': ['Death',      'Star',       ], 'result': 'Lovers'      },
    {'source': ['Death',      'Moon',       ], 'result': 'Priestess'   },
    {'source': ['Death',      'Sun',        ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Temperance', ], 'result': 'Temperance'  },
    {'source': ['Temperance', 'Devil',      ], 'result': 'Hermit'      },
    {'source': ['Temperance', 'Tower',      ], 'result': 'Star'        },
    {'source': ['Temperance', 'Star',       ], 'result': 'Heirophant'  },
    {'source': ['Temperance', 'Moon',       ], 'result': 'Hanged Man'  },
    {'source': ['Temperance', 'Sun',        ], 'result': 'Hermit'      },
    {'source': ['Devil',      'Devil',      ], 'result': 'Devil'       },
    {'source': ['Devil',      'Tower',      ], 'result': 'Emperor'     },
    {'source': ['Devil',      'Star',       ], 'result': 'Emperor'     },
    {'source': ['Devil',      'Moon',       ], 'result': 'Empress'     },
    {'source': ['Devil',      'Sun',        ], 'result': 'Heirophant'  },
    {'source': ['Tower',      'Tower',      ], 'result': 'Tower'       },
    {'source': ['Tower',      'Star',       ], 'result': 'Hanged Man'  },
    {'source': ['Tower',      'Moon',       ], 'result': 'Priestess'   },
    {'source': ['Tower',      'Sun',        ], 'result': 'Chariot'     },
    {'source': ['Star',       'Star',       ], 'result': 'Star'        },
    {'source': ['Star',       'Moon',       ], 'result': 'Emperor'     },
    {'source': ['Star',       'Sun',        ], 'result': 'Moon'        },
    {'source': ['Moon',       'Moon',       ], 'result': 'Moon'        },
    {'source': ['Moon',       'Sun',        ], 'result': 'Strength'    },
    {'source': ['Sun',        'Sun',        ], 'result': 'Sun'         },
    {'source': ['Judgement',  'Judgement',  ], 'result': 'Judgement'   },
    ];

const arcana3Combos = [
    {'source': ['Magician',   'Fool',       ], 'result': 'Fortune'     },
    {'source': ['Priestess',  'Fool',       ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Magician',   ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Fool',       ], 'result': 'Judgement'   },
    {'source': ['Empress',    'Magician',   ], 'result': 'Sun'         },
    {'source': ['Empress',    'Priestess',  ], 'result': 'Temperance'  },
    {'source': ['Emperor',    'Fool',       ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Magician',   ], 'result': 'Death'       },
    {'source': ['Emperor',    'Priestess',  ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Empress',    ], 'result': 'Fool'        },
    {'source': ['Heirophant', 'Fool',       ], 'result': 'Tower'       },
    {'source': ['Heirophant', 'Magician',   ], 'result': 'Judgement'   },
    {'source': ['Heirophant', 'Priestess',  ], 'result': 'Empress'     },
    {'source': ['Heirophant', 'Empress',    ], 'result': 'Priestess'   },
    {'source': ['Heirophant', 'Emperor',    ], 'result': 'Chariot'     },
    {'source': ['Lovers',     'Fool',       ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Magician',   ], 'result': 'Temperance'  },
    {'source': ['Lovers',     'Priestess',  ], 'result': 'Hanged Man'  },
    {'source': ['Lovers',     'Empress',    ], 'result': 'Fool'        },
    {'source': ['Lovers',     'Emperor',    ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Heirophant', ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Fool',       ], 'result': 'Lovers'      },
    {'source': ['Chariot',    'Magician',   ], 'result': 'Emperor'     },
    {'source': ['Chariot',    'Priestess',  ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Empress',    ], 'result': 'Emperor'     },
    {'source': ['Chariot',    'Emperor',    ], 'result': 'Tower'       },
    {'source': ['Chariot',    'Heirophant', ], 'result': 'Judgement'   },
    {'source': ['Chariot',    'Lovers',     ], 'result': 'Heirophant'  },
    {'source': ['Justice',    'Fool',       ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Magician',   ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Priestess',  ], 'result': 'Hermit'      },
    {'source': ['Justice',    'Empress',    ], 'result': 'Death'       },
    {'source': ['Justice',    'Emperor',    ], 'result': 'Devil'       },
    {'source': ['Justice',    'Heirophant', ], 'result': 'Magician'    },
    {'source': ['Justice',    'Lovers',     ], 'result': 'Magician'    },
    {'source': ['Justice',    'Chariot',    ], 'result': 'Temperance'  },
    {'source': ['Hermit',     'Fool',       ], 'result': 'Strength'    },
    {'source': ['Hermit',     'Magician',   ], 'result': 'Empress'     },
    {'source': ['Hermit',     'Priestess',  ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Empress',    ], 'result': 'Fool'        },
    {'source': ['Hermit',     'Emperor',    ], 'result': 'Moon'        },
    {'source': ['Hermit',     'Heirophant', ], 'result': 'Lovers'      },
    {'source': ['Hermit',     'Lovers',     ], 'result': 'Heirophant'  },
    {'source': ['Hermit',     'Chariot',    ], 'result': 'Priestess'   },
    {'source': ['Hermit',     'Justice',    ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Fool',       ], 'result': 'Judgement'   },
    {'source': ['Fortune',    'Magician',   ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Priestess',  ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Empress',    ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Emperor',    ], 'result': 'Priestess'   },
    {'source': ['Fortune',    'Heirophant', ], 'result': 'Hanged Man'  },
    {'source': ['Fortune',    'Lovers',     ], 'result': 'Hanged Man'  },
    {'source': ['Fortune',    'Chariot',    ], 'result': 'Temperance'  },
    {'source': ['Fortune',    'Justice',    ], 'result': 'Priestess'   },
    {'source': ['Fortune',    'Hermit',     ], 'result': 'Judgement'   },
    {'source': ['Strength',   'Fool',       ], 'result': 'Empress'     },
    {'source': ['Strength',   'Magician',   ], 'result': 'Tower'       },
    {'source': ['Strength',   'Priestess',  ], 'result': 'Empress'     },
    {'source': ['Strength',   'Empress',    ], 'result': 'Fool'        },
    {'source': ['Strength',   'Emperor',    ], 'result': 'Hermit'      },
    {'source': ['Strength',   'Heirophant', ], 'result': 'Moon'        },
    {'source': ['Strength',   'Lovers',     ], 'result': 'Fool'        },
    {'source': ['Strength',   'Chariot',    ], 'result': 'Magician'    },
    {'source': ['Strength',   'Justice',    ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Hermit',     ], 'result': 'Justice'     },
    {'source': ['Strength',   'Fortune',    ], 'result': 'Priestess'   },
    {'source': ['Hanged Man', 'Fool',       ], 'result': 'Star'        },
    {'source': ['Hanged Man', 'Magician',   ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Priestess',  ], 'result': 'Chariot'     },
    {'source': ['Hanged Man', 'Empress',    ], 'result': 'Sun'         },
    {'source': ['Hanged Man', 'Emperor',    ], 'result': 'Heirophant'  },
    {'source': ['Hanged Man', 'Heirophant', ], 'result': 'Star'        },
    {'source': ['Hanged Man', 'Lovers',     ], 'result': 'Justice'     },
    {'source': ['Hanged Man', 'Chariot',    ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Justice',    ], 'result': 'Star'        },
    {'source': ['Hanged Man', 'Hermit',     ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Fortune',    ], 'result': 'Fool'        },
    {'source': ['Hanged Man', 'Strength',   ], 'result': 'Star'        },
    {'source': ['Death',      'Fool',       ], 'result': 'Star'        },
    {'source': ['Death',      'Magician',   ], 'result': 'Fool'        },
    {'source': ['Death',      'Priestess',  ], 'result': 'Chariot'     },
    {'source': ['Death',      'Empress',    ], 'result': 'Heirophant'  },
    {'source': ['Death',      'Emperor',    ], 'result': 'Strength'    },
    {'source': ['Death',      'Heirophant', ], 'result': 'Magician'    },
    {'source': ['Death',      'Lovers',     ], 'result': 'Hanged Man'  },
    {'source': ['Death',      'Chariot',    ], 'result': 'Devil'       },
    {'source': ['Death',      'Justice',    ], 'result': 'Devil'       },
    {'source': ['Death',      'Hermit',     ], 'result': 'Magician'    },
    {'source': ['Death',      'Fortune',    ], 'result': 'Moon'        },
    {'source': ['Death',      'Strength',   ], 'result': 'Empress'     },
    {'source': ['Death',      'Hanged Man', ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Fool',       ], 'result': 'Justice'     },
    {'source': ['Temperance', 'Magician',   ], 'result': 'Sun'         },
    {'source': ['Temperance', 'Priestess',  ], 'result': 'Lovers'      },
    {'source': ['Temperance', 'Empress',    ], 'result': 'Emperor'     },
    {'source': ['Temperance', 'Emperor',    ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Heirophant', ], 'result': 'Emperor'     },
    {'source': ['Temperance', 'Lovers',     ], 'result': 'Fortune'     },
    {'source': ['Temperance', 'Chariot',    ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Justice',    ], 'result': 'Magician'    },
    {'source': ['Temperance', 'Hermit',     ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Fortune',    ], 'result': 'Tower'       },
    {'source': ['Temperance', 'Strength',   ], 'result': 'Emperor'     },
    {'source': ['Temperance', 'Hanged Man', ], 'result': 'Justice'     },
    {'source': ['Temperance', 'Death',      ], 'result': 'Fool'        },
    {'source': ['Devil',      'Fool',       ], 'result': 'Lovers'      },
    {'source': ['Devil',      'Magician',   ], 'result': 'Chariot'     },
    {'source': ['Devil',      'Priestess',  ], 'result': 'Hermit'      },
    {'source': ['Devil',      'Empress',    ], 'result': 'Fool'        },
    {'source': ['Devil',      'Emperor',    ], 'result': 'Death'       },
    {'source': ['Devil',      'Heirophant', ], 'result': 'Moon'        },
    {'source': ['Devil',      'Lovers',     ], 'result': 'Tower'       },
    {'source': ['Devil',      'Chariot',    ], 'result': 'Emperor'     },
    {'source': ['Devil',      'Justice',    ], 'result': 'Priestess'   },
    {'source': ['Devil',      'Hermit',     ], 'result': 'Death'       },
    {'source': ['Devil',      'Fortune',    ], 'result': 'Tower'       },
    {'source': ['Devil',      'Strength',   ], 'result': 'Lovers'      },
    {'source': ['Devil',      'Hanged Man', ], 'result': 'Justice'     },
    {'source': ['Devil',      'Death',      ], 'result': 'Lovers'      },
    {'source': ['Devil',      'Temperance', ], 'result': 'Justice'     },
    {'source': ['Tower',      'Fool',       ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Magician',   ], 'result': 'Emperor'     },
    {'source': ['Tower',      'Priestess',  ], 'result': 'Moon'        },
    {'source': ['Tower',      'Empress',    ], 'result': 'Judgement'   },
    {'source': ['Tower',      'Emperor',    ], 'result': 'Chariot'     },
    {'source': ['Tower',      'Heirophant', ], 'result': 'Emperor'     },
    {'source': ['Tower',      'Lovers',     ], 'result': 'Judgement'   },
    {'source': ['Tower',      'Chariot',    ], 'result': 'Heirophant'  },
    {'source': ['Tower',      'Justice',    ], 'result': 'Chariot'     },
    {'source': ['Tower',      'Hermit',     ], 'result': 'Empress'     },
    {'source': ['Tower',      'Fortune',    ], 'result': 'Magician'    },
    {'source': ['Tower',      'Strength',   ], 'result': 'Devil'       },
    {'source': ['Tower',      'Hanged Man', ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Death',      ], 'result': 'Justice'     },
    {'source': ['Tower',      'Temperance', ], 'result': 'Judgement'   },
    {'source': ['Tower',      'Devil',      ], 'result': 'Star'        },
    {'source': ['Star',       'Fool',       ], 'result': 'Hermit'      },
    {'source': ['Star',       'Magician',   ], 'result': 'Heirophant'  },
    {'source': ['Star',       'Priestess',  ], 'result': 'Empress'     },
    {'source': ['Star',       'Empress',    ], 'result': 'Fool'        },
    {'source': ['Star',       'Emperor',    ], 'result': 'Sun'         },
    {'source': ['Star',       'Heirophant', ], 'result': 'Lovers'      },
    {'source': ['Star',       'Lovers',     ], 'result': 'Heirophant'  },
    {'source': ['Star',       'Chariot',    ], 'result': 'Magician'    },
    {'source': ['Star',       'Justice',    ], 'result': 'Sun'         },
    {'source': ['Star',       'Hermit',     ], 'result': 'Death'       },
    {'source': ['Star',       'Fortune',    ], 'result': 'Magician'    },
    {'source': ['Star',       'Strength',   ], 'result': 'Devil'       },
    {'source': ['Star',       'Hanged Man', ], 'result': 'Sun'         },
    {'source': ['Star',       'Death',      ], 'result': 'Fortune'     },
    {'source': ['Star',       'Temperance', ], 'result': 'Heirophant'  },
    {'source': ['Star',       'Devil',      ], 'result': 'Fortune'     },
    {'source': ['Star',       'Tower',      ], 'result': 'Hermit'      },
    {'source': ['Moon',       'Fool',       ], 'result': 'Empress'     },
    {'source': ['Moon',       'Magician',   ], 'result': 'Sun'         },
    {'source': ['Moon',       'Priestess',  ], 'result': 'Empress'     },
    {'source': ['Moon',       'Empress',    ], 'result': 'Moon'        },
    {'source': ['Moon',       'Emperor',    ], 'result': 'Strength'    },
    {'source': ['Moon',       'Heirophant', ], 'result': 'Magician'    },
    {'source': ['Moon',       'Lovers',     ], 'result': 'Hanged Man'  },
    {'source': ['Moon',       'Chariot',    ], 'result': 'Fool'        },
    {'source': ['Moon',       'Justice',    ], 'result': 'Star'        },
    {'source': ['Moon',       'Hermit',     ], 'result': 'Temperance'  },
    {'source': ['Moon',       'Fortune',    ], 'result': 'Strength'    },
    {'source': ['Moon',       'Strength',   ], 'result': 'Heirophant'  },
    {'source': ['Moon',       'Hanged Man', ], 'result': 'Magician'    },
    {'source': ['Moon',       'Death',      ], 'result': 'Hanged Man'  },
    {'source': ['Moon',       'Temperance', ], 'result': 'Hanged Man'  },
    {'source': ['Moon',       'Devil',      ], 'result': 'Death'       },
    {'source': ['Moon',       'Tower',      ], 'result': 'Hanged Man'  },
    {'source': ['Moon',       'Star',       ], 'result': 'Death'       },
    {'source': ['Sun',        'Fool',       ], 'result': 'Empress'     },
    {'source': ['Sun',        'Magician',   ], 'result': 'Fortune'     },
    {'source': ['Sun',        'Priestess',  ], 'result': 'Fool'        },
    {'source': ['Sun',        'Empress',    ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Emperor',    ], 'result': 'Devil'       },
    {'source': ['Sun',        'Heirophant', ], 'result': 'Magician'    },
    {'source': ['Sun',        'Lovers',     ], 'result': 'Justice'     },
    {'source': ['Sun',        'Chariot',    ], 'result': 'Priestess'   },
    {'source': ['Sun',        'Justice',    ], 'result': 'Judgement'   },
    {'source': ['Sun',        'Hermit',     ], 'result': 'Tower'       },
    {'source': ['Sun',        'Fortune',    ], 'result': 'Chariot'     },
    {'source': ['Sun',        'Strength',   ], 'result': 'Tower'       },
    {'source': ['Sun',        'Hanged Man', ], 'result': 'Empress'     },
    {'source': ['Sun',        'Death',      ], 'result': 'Empress'     },
    {'source': ['Sun',        'Temperance', ], 'result': 'Fortune'     },
    {'source': ['Sun',        'Devil',      ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Tower',      ], 'result': 'Death'       },
    {'source': ['Sun',        'Star',       ], 'result': 'Chariot'     },
    {'source': ['Sun',        'Moon',       ], 'result': 'Death'       },
    {'source': ['Judgement',  'Fool',       ], 'result': 'Temperance'  },
    {'source': ['Judgement',  'Magician',   ], 'result': 'Sun'         },
    {'source': ['Judgement',  'Priestess',  ], 'result': 'Temperance'  },
    {'source': ['Judgement',  'Empress',    ], 'result': 'Star'        },
    {'source': ['Judgement',  'Emperor',    ], 'result': 'Hanged Man'  },
    {'source': ['Judgement',  'Heirophant', ], 'result': 'Fool'        },
    {'source': ['Judgement',  'Lovers',     ], 'result': 'Emperor'     },
    {'source': ['Judgement',  'Chariot',    ], 'result': 'Tower'       },
    {'source': ['Judgement',  'Justice',    ], 'result': 'Sun'         },
    {'source': ['Judgement',  'Hermit',     ], 'result': 'Temperance'  },
    {'source': ['Judgement',  'Fortune',    ], 'result': 'Fool'        },
    {'source': ['Judgement',  'Strength',   ], 'result': 'Temperance'  },
    {'source': ['Judgement',  'Hanged Man', ], 'result': 'Fool'        },
    {'source': ['Judgement',  'Death',      ], 'result': 'Strength'    },
    {'source': ['Judgement',  'Temperance', ], 'result': 'Chariot'     },
    {'source': ['Judgement',  'Devil',      ], 'result': 'Death'       },
    {'source': ['Judgement',  'Tower',      ], 'result': 'Lovers'      },
    {'source': ['Judgement',  'Star',       ], 'result': 'Lovers'      },
    {'source': ['Judgement',  'Moon',       ], 'result': 'Hermit'      },
    {'source': ['Judgement',  'Sun',        ], 'result': 'Chariot'     },
    ];

const specialCombos = [
    {'result': 'Izanagi', 'sources': ['Yomotsu-Shikome', 'Obariyon']},
    {'result': 'Black Frost', 'sources': ['Jack Frost', 'Pyro Jack', 'King Frost', 'Pixie', 'Ghoul']},
    {'result': 'Pixie', 'sources': ['Orobas', 'Jack Frost']},
    {'result': 'Kohryu', 'sources': ['Genbu', 'Seiryu', 'Suzaku', 'Byakko']},
    {'result': 'Slime', 'sources': ['Eligor', 'Nata Taishi']},
    {'result': 'Futsunushi', 'sources': ['Ares', 'Triglav', 'Kin-ki', 'Atavaka', 'Neko Shogun']},
    {'result': 'Ongyo-ki', 'sources': ['Oni', 'Fuu-ki', 'Kin-ki', 'Sui-ki']},
    {'result': 'Norn', 'sources': ['Atropos', 'Lachesis', 'Clotho']},
    {'result': 'Yatsufusa', 'sources': ['Makami', 'Orthrus', 'Mothman', 'Thoth', 'Narasimha']},
    {'result': 'Alice', 'sources': ['Nebiros', 'Belial']},
    {'result': 'Mahakala', 'sources': ['Matador', 'White Rider', 'Mother Harlot', 'Daisoujou', 'Hell Biker', 'Trumpeter']},
    {'result': 'Ukobach', 'sources': ['Lilim', 'Vetala']},
    {'result': 'Beelzebub', 'sources': ['Pazuzu', 'Belphegor', 'Belial', 'Mot', 'Seth', 'Baal Zebul']},
    {'result': 'Yoshitsune', 'sources': ['Masakado', 'Shiki-Ouji', 'Oukuninushi', 'Hachiman', 'Hitokoto-Nushi']},
    {'result': 'Shiva', 'sources': ['Rangda', 'Barong']},
    {'result': 'Neko Shogun', 'sources': ['Saki Mitama', 'Ara Mitama', 'Kusi Mitama', 'Nigi Mitama']},
    {'result': 'Tam Lin', 'sources': ['Phoenix', 'Gdon', 'Yatagarasu', 'Narasimha']},
    {'result': 'Trumpeter', 'sources': ['Matador', 'White Rider', 'Daisoujou', 'Taotie', 'Pabilsag', 'Taowu']},
    {'result': 'Ardha', 'sources': ['Parvati', 'Shiva']},
    {'result': 'Lucifer', 'sources': ['Ananta', 'Anubis', 'Trumpeter', 'Michael', 'Satan', 'Metatron']},
    {'result': 'Izanagi-no-Okami', 'sources': ['Izanagi', 'Sandman', 'Nata Taishi', 'Girimehkala', 'Norn', 'Oukuninushi', 'Orthrus', 'Kartikeya', 'Mithra', 'Tzitzimitl', 'Cu Chulainn', 'Legion']},
    ];
