// Derived from:
//  http://www.gamefaqs.com/ps2/937269-shin-megami-tensei-persona-3-fes/faqs/52659
//  http://www.gamefaqs.com/ps2/937269-shin-megami-tensei-persona-3-fes/faqs/53404
//  http://www.gamefaqs.com/ps2/937269-shin-megami-tensei-persona-3-fes/faqs/52531

const personae = [
    {'name': 'Orpheus',         'level':  1, 'arcana': 'Fool'},
    {'name': 'Slime',           'level': 12, 'arcana': 'Fool'},
    {'name': 'Legion',          'level': 22, 'arcana': 'Fool'},
    {'name': 'Black Frost',     'level': 34, 'arcana': 'Fool'},
    {'name': 'Ose',             'level': 44, 'arcana': 'Fool'},
    {'name': 'Decarabia',       'level': 50, 'arcana': 'Fool'},
    {'name': 'Loki',            'level': 58, 'arcana': 'Fool'},
    {'name': 'Susano-o',        'level': 76, 'arcana': 'Fool'},
    {'name': 'Orpheus Telos',   'level': 90, 'arcana': 'Fool'},
    {'name': 'Nekomata',        'level':  5, 'arcana': 'Magician'},
    {'name': 'Jack Frost',      'level':  8, 'arcana': 'Magician'},
    {'name': 'Pyro Jack',       'level': 14, 'arcana': 'Magician'},
    {'name': 'Hua Po',          'level': 20, 'arcana': 'Magician'},
    {'name': 'Sati',            'level': 28, 'arcana': 'Magician'},
    {'name': 'Orobas',          'level': 34, 'arcana': 'Magician'},
    {'name': 'Rangda',          'level': 40, 'arcana': 'Magician'},
    {'name': 'Surt',            'level': 52, 'arcana': 'Magician'},
    {'name': 'Apsaras',         'level':  3, 'arcana': 'Priestess'},
    {'name': 'Unicorn',         'level': 11, 'arcana': 'Priestess'},
    {'name': 'High Pixie',      'level': 21, 'arcana': 'Priestess'},
    {'name': 'Sarasvati',       'level': 27, 'arcana': 'Priestess'},
    {'name': 'Ganga',           'level': 35, 'arcana': 'Priestess'},
    {'name': 'Parvati',         'level': 47, 'arcana': 'Priestess'},
    {'name': 'Kikuri-hime',     'level': 53, 'arcana': 'Priestess'},
    {'name': 'Scathach',        'level': 64, 'arcana': 'Priestess'},
    {'name': 'Leanan Sidhe',    'level': 33, 'arcana': 'Empress'},
    {'name': 'Yaksini',         'level': 50, 'arcana': 'Empress'},
    {'name': 'Laksmi',          'level': 57, 'arcana': 'Empress'},
    {'name': 'Hariti',          'level': 62, 'arcana': 'Empress'},
    {'name': 'Gabriel',         'level': 69, 'arcana': 'Empress'},
    {'name': 'Mother Harlot',   'level': 74, 'arcana': 'Empress'},
    {'name': 'Skadi',           'level': 80, 'arcana': 'Empress'},
    {'name': 'Alilat',          'level': 84, 'arcana': 'Empress'},
    {'name': 'Forneus',         'level':  7, 'arcana': 'Emperor'},
    {'name': 'Oberon',          'level': 15, 'arcana': 'Emperor'},
    {'name': 'Take-mikazuchi',  'level': 24, 'arcana': 'Emperor'},
    {'name': 'King Frost',      'level': 30, 'arcana': 'Emperor'},
    {'name': 'Raja Naga',       'level': 36, 'arcana': 'Emperor'},
    {'name': 'Kingu',           'level': 46, 'arcana': 'Emperor'},
    {'name': 'Barong',          'level': 52, 'arcana': 'Emperor'},
    {'name': 'Odin',            'level': 57, 'arcana': 'Emperor'},
    {'name': 'Omoikane',        'level':  7, 'arcana': 'Hierophant'},
    {'name': 'Berith',          'level': 13, 'arcana': 'Hierophant'},
    {'name': 'Shiisaa',         'level': 26, 'arcana': 'Hierophant'},
    {'name': 'Flauros',         'level': 33, 'arcana': 'Hierophant'},
    {'name': 'Thoth',           'level': 41, 'arcana': 'Hierophant'},
    {'name': 'Hokuto Seikun',   'level': 47, 'arcana': 'Hierophant'},
    {'name': 'Daisoujou',       'level': 53, 'arcana': 'Hierophant'},
    {'name': 'Kohryu',          'level': 66, 'arcana': 'Hierophant'},
    {'name': 'Pixie',           'level':  2, 'arcana': 'Lovers'},
    {'name': 'Alp',             'level':  6, 'arcana': 'Lovers'},
    {'name': 'Narcissus',       'level': 20, 'arcana': 'Lovers'},
    {'name': 'Queen Mab',       'level': 27, 'arcana': 'Lovers'},
    {'name': 'Saki Mitama',     'level': 39, 'arcana': 'Lovers'},
    {'name': 'Titania',         'level': 48, 'arcana': 'Lovers'},
    {'name': 'Raphael',         'level': 61, 'arcana': 'Lovers'},
    {'name': 'Cybele',          'level': 68, 'arcana': 'Lovers'},
    {'name': 'Ara Mitama',      'level':  6, 'arcana': 'Chariot'},
    {'name': 'Chimera',         'level':  9, 'arcana': 'Chariot'},
    {'name': 'Zouchouten',      'level': 14, 'arcana': 'Chariot'},
    {'name': 'Ares',            'level': 19, 'arcana': 'Chariot'},
    {'name': 'Oumitsunu',       'level': 30, 'arcana': 'Chariot'},
    {'name': 'Nata Taishi',     'level': 37, 'arcana': 'Chariot'},
    {'name': 'Koumokuten',      'level': 43, 'arcana': 'Chariot'},
    {'name': 'Thor',            'level': 53, 'arcana': 'Chariot'},
    {'name': 'Angel',           'level':  4, 'arcana': 'Justice'},
    {'name': 'Archangel',       'level': 10, 'arcana': 'Justice'},
    {'name': 'Principality',    'level': 16, 'arcana': 'Justice'},
    {'name': 'Power',           'level': 25, 'arcana': 'Justice'},
    {'name': 'Virtue',          'level': 32, 'arcana': 'Justice'},
    {'name': 'Dominion',        'level': 42, 'arcana': 'Justice'},
    {'name': 'Throne',          'level': 51, 'arcana': 'Justice'},
    {'name': 'Melchizedek',     'level': 59, 'arcana': 'Justice'},
    {'name': 'Yomotsu Shikome', 'level':  9, 'arcana': 'Hermit'},
    {'name': 'Naga',            'level': 17, 'arcana': 'Hermit'},
    {'name': 'Lamia',           'level': 25, 'arcana': 'Hermit'},
    {'name': 'Mothman',         'level': 32, 'arcana': 'Hermit'},
    {'name': 'Taraka',          'level': 38, 'arcana': 'Hermit'},
    {'name': 'Kurama Tengu',    'level': 44, 'arcana': 'Hermit'},
    {'name': 'Nebiros',         'level': 50, 'arcana': 'Hermit'},
    {'name': 'Kumbhanda',       'level': 56, 'arcana': 'Hermit'},
    {'name': 'Arahabaki',       'level': 60, 'arcana': 'Hermit'},
    {'name': 'Fortuna',         'level': 17, 'arcana': 'Fortune'},
    {'name': 'Empusa',          'level': 23, 'arcana': 'Fortune'},
    {'name': 'Kusi Mitama',     'level': 29, 'arcana': 'Fortune'},
    {'name': 'Clotho',          'level': 38, 'arcana': 'Fortune'},
    {'name': 'Lachesis',        'level': 45, 'arcana': 'Fortune'},
    {'name': 'Atropos',         'level': 54, 'arcana': 'Fortune'},
    {'name': 'Norn',            'level': 62, 'arcana': 'Fortune'},
    {'name': 'Valkyrie',        'level': 11, 'arcana': 'Strength'},
    {'name': 'Rakshasa',        'level': 16, 'arcana': 'Strength'},
    {'name': 'Titan',           'level': 23, 'arcana': 'Strength'},
    {'name': 'Jikokuten',       'level': 29, 'arcana': 'Strength'},
    {'name': 'Hanuman',         'level': 37, 'arcana': 'Strength'},
    {'name': 'Narasimha',       'level': 46, 'arcana': 'Strength'},
    {'name': 'Kali',            'level': 55, 'arcana': 'Strength'},
    {'name': 'Siegfried',       'level': 59, 'arcana': 'Strength'},
    {'name': 'Inugami',         'level': 10, 'arcana': 'Hanged Man'},
    {'name': 'Take-minakata',   'level': 21, 'arcana': 'Hanged Man'},
    {'name': 'Orthrus',         'level': 28, 'arcana': 'Hanged Man'},
    {'name': 'Vasuki',          'level': 38, 'arcana': 'Hanged Man'},
    {'name': 'Ubelluris',       'level': 48, 'arcana': 'Hanged Man'},
    {'name': 'Hecatoncheires',  'level': 54, 'arcana': 'Hanged Man'},
    {'name': 'Hell Biker',      'level': 60, 'arcana': 'Hanged Man'},
    {'name': 'Attis',           'level': 67, 'arcana': 'Hanged Man'},
    {'name': 'Ghoul',           'level': 18, 'arcana': 'Death'},
    {'name': 'Pale Rider',      'level': 24, 'arcana': 'Death'},
    {'name': 'Loa',             'level': 31, 'arcana': 'Death'},
    {'name': 'Samael',          'level': 37, 'arcana': 'Death'},
    {'name': 'Mot',             'level': 45, 'arcana': 'Death'},
    {'name': 'Alice',           'level': 56, 'arcana': 'Death'},
    {'name': 'Thanatos',        'level': 64, 'arcana': 'Death'},
    {'name': 'Nigi Mitama',     'level': 12, 'arcana': 'Temperance'},
    {'name': 'Mithra',          'level': 22, 'arcana': 'Temperance'},
    {'name': 'Genbu',           'level': 29, 'arcana': 'Temperance'},
    {'name': 'Seiryuu',         'level': 36, 'arcana': 'Temperance'},
    {'name': 'Okuninushi',      'level': 44, 'arcana': 'Temperance'},
    {'name': 'Suzaku',          'level': 51, 'arcana': 'Temperance'},
    {'name': 'Byakko',          'level': 57, 'arcana': 'Temperance'},
    {'name': 'Yurlungur',       'level': 64, 'arcana': 'Temperance'},
    {'name': 'Lilim',           'level':  8, 'arcana': 'Devil'},
    {'name': 'Vetala',          'level': 24, 'arcana': 'Devil'},
    {'name': 'Incubus',         'level': 34, 'arcana': 'Devil'},
    {'name': 'Succubus',        'level': 43, 'arcana': 'Devil'},
    {'name': 'Pazuzu',          'level': 52, 'arcana': 'Devil'},
    {'name': 'Lilith',          'level': 61, 'arcana': 'Devil'},
    {'name': 'Abaddon',         'level': 68, 'arcana': 'Devil'},
    {'name': 'Beelzebub',       'level': 81, 'arcana': 'Devil'},
    {'name': 'Eligor',          'level': 31, 'arcana': 'Tower'},
    {'name': 'Cu Chulainn',     'level': 40, 'arcana': 'Tower'},
    {'name': 'Bishamonten',     'level': 60, 'arcana': 'Tower'},
    {'name': 'Seiten Taisei',   'level': 67, 'arcana': 'Tower'},
    {'name': 'Masakado',        'level': 73, 'arcana': 'Tower'},
    {'name': 'Mara',            'level': 77, 'arcana': 'Tower'},
    {'name': 'Shiva',           'level': 82, 'arcana': 'Tower'},
    {'name': 'Chi You',         'level': 86, 'arcana': 'Tower'},
    {'name': 'Nandi',           'level': 39, 'arcana': 'Star'},
    {'name': 'Kaiwan',          'level': 49, 'arcana': 'Star'},
    {'name': 'Ganesha',         'level': 58, 'arcana': 'Star'},
    {'name': 'Garuda',          'level': 65, 'arcana': 'Star'},
    {'name': 'Kartikeya',       'level': 70, 'arcana': 'Star'},
    {'name': 'Saturnus',        'level': 78, 'arcana': 'Star'},
    {'name': 'Helel',           'level': 88, 'arcana': 'Star'},
    {'name': 'Gurr',            'level': 15, 'arcana': 'Moon'},
    {'name': 'Yamatano-orochi', 'level': 26, 'arcana': 'Moon'},
    {'name': 'Girimehkala',     'level': 42, 'arcana': 'Moon'},
    {'name': 'Dionysus',        'level': 48, 'arcana': 'Moon'},
    {'name': 'Chernobog',       'level': 58, 'arcana': 'Moon'},
    {'name': 'Seth',            'level': 66, 'arcana': 'Moon'},
    {'name': 'Baal Zebul',      'level': 71, 'arcana': 'Moon'},
    {'name': 'Sandalphon',      'level': 74, 'arcana': 'Moon'},
    {'name': 'Yatagarasu',      'level': 30, 'arcana': 'Sun'},
    {'name': 'Quetzalcoatl',    'level': 43, 'arcana': 'Sun'},
    {'name': 'Jatayu',          'level': 55, 'arcana': 'Sun'},
    {'name': 'Horus',           'level': 63, 'arcana': 'Sun'},
    {'name': 'Sparna',          'level': 70, 'arcana': 'Sun'},
    {'name': 'Vishnu',          'level': 78, 'arcana': 'Sun'},
    {'name': 'Asura',           'level': 85, 'arcana': 'Sun'},
    {'name': 'Anubis',          'level': 59, 'arcana': 'Judgment'},
    {'name': 'Trumpeter',       'level': 65, 'arcana': 'Judgment'},
    {'name': 'Michael',         'level': 72, 'arcana': 'Judgment'},
    {'name': 'Satan',           'level': 79, 'arcana': 'Judgment'},
    {'name': 'Lucifer',         'level': 89, 'arcana': 'Judgment'},
    {'name': 'Messiah',         'level': 90, 'arcana': 'Judgment'},
    {'name': 'Uriel',           'level': 63, 'arcana': 'Aeon'},
    {'name': 'Nidhogg',         'level': 69, 'arcana': 'Aeon'},
    {'name': 'Ananta',          'level': 75, 'arcana': 'Aeon'},
    {'name': 'Atavaka',         'level': 80, 'arcana': 'Aeon'},
    {'name': 'Metatron',        'level': 87, 'arcana': 'Aeon'},
    ];

const personaeNames = (function() {
  var personaeNames_ = [];
  for (var i = 0, persona = null; persona = personae[i]; i++) {
    personaeNames_.push(persona.name);
  }
  personaeNames_.sort();
  return personaeNames_;
})();

const personaeByName = (function() {
  var personaeByName_ = {};
  for (var i = 0, persona = null; persona = personae[i]; i++) {
    personaeByName_[persona.name] = persona;
  }
  return personaeByName_;
})();

const personaeByArcana = (function() {
  var personaeByArcana_ = {};
  for (var i = 0, persona = null; persona = personae[i]; i++) {
    if (!personaeByArcana_[persona.arcana]) {
      personaeByArcana_[persona.arcana] = [];
    }
    personaeByArcana_[persona.arcana].push(persona);
  }
  return personaeByArcana_;
})();

const arcana = (function() {
  var arcana_ = [];
  var arcanaNum = 0;
  var lastArcana = null;
  for (var i = 0, persona = null; persona = personae[i]; i++) {
    if (persona.arcana != lastArcana) {
      lastArcana = persona.arcana;
      arcana_.push(persona.arcana);
    }
  }
  return arcana_;
})();

const arcana2Combos = [
    {'source': ['Fool',       'Fool'        ], 'result': 'Fool'        },
    {'source': ['Fool',       'Magician'    ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Fool',       'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Fool',       'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Lovers'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Fool',       'Justice'     ], 'result': 'Lovers'      },
    {'source': ['Fool',       'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Fortune'     ], 'result': 'Justice'     },
    {'source': ['Fool',       'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Fool',       'Hanged Man'  ], 'result': 'Magician'    },
    {'source': ['Fool',       'Death'       ], 'result': 'Strength'    },
    {'source': ['Fool',       'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Devil'       ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fool',       'Star'        ], 'result': 'Aeon'        },
    {'source': ['Fool',       'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Fool',       'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fool',       'Aeon'        ], 'result': 'Death'       },
    {'source': ['Magician',   'Fool'        ], 'result': 'Hierophant'  },
    {'source': ['Magician',   'Magician'    ], 'result': 'Magician'    },
    {'source': ['Magician',   'Priestess'   ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Empress'     ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Emperor'     ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Magician',   'Lovers'      ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Magician',   'Justice'     ], 'result': 'Hierophant'  },
    {'source': ['Magician',   'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Magician',   'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Magician',   'Temperance'  ], 'result': 'Death'       },
    {'source': ['Magician',   'Devil'       ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Tower'       ], 'result': 'Empress'     },
    {'source': ['Magician',   'Star'        ], 'result': 'Empress'     },
    {'source': ['Magician',   'Moon'        ], 'result': 'Priestess'   },
    {'source': ['Magician',   'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Fool'        ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Magician'    ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Priestess'   ], 'result': 'Priestess'   },
    {'source': ['Priestess',  'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Emperor'     ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Lovers'      ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Chariot'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Justice'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Strength'    ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Death'       ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Star'        ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Moon'        ], 'result': 'Star'        },
    {'source': ['Priestess',  'Sun'         ], 'result': 'Star'        },
    {'source': ['Priestess',  'Judgment'    ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Empress',    'Fool'        ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Magician'    ], 'result': 'Hanged Man'  },
    {'source': ['Empress',    'Priestess'   ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Empress'     ], 'result': 'Empress'     },
    {'source': ['Empress',    'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Lovers'      ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Empress',    'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Empress',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Empress',    'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Hanged Man'  ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Death'       ], 'result': 'Devil'       },
    {'source': ['Empress',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Devil'       ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Tower'       ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Star'        ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Moon'        ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Fool'        ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Magician'    ], 'result': 'Temperance'  },
    {'source': ['Emperor',    'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Emperor'     ], 'result': 'Emperor'     },
    {'source': ['Emperor',    'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Lovers'      ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Chariot'     ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Justice'     ], 'result': 'Devil'       },
    {'source': ['Emperor',    'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Emperor',    'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Star'        ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Sun'         ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Judgment'    ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Fool'        ], 'result': 'Hermit'      },
    {'source': ['Hierophant', 'Magician'    ], 'result': 'Hermit'      },
    {'source': ['Hierophant', 'Priestess'   ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Empress'     ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Hierophant'  ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Lovers'      ], 'result': 'Magician'    },
    {'source': ['Hierophant', 'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Hierophant', 'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Hanged Man'  ], 'result': 'Lovers'      },
    {'source': ['Hierophant', 'Death'       ], 'result': 'Empress'     },
    {'source': ['Hierophant', 'Temperance'  ], 'result': 'Strength'    },
    {'source': ['Hierophant', 'Tower'       ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Star'        ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Judgment'    ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Fool'        ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Magician'    ], 'result': 'Emperor'     },
    {'source': ['Lovers',     'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Lovers',     'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Lovers',     'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Lovers',     'Hierophant'  ], 'result': 'Magician'    },
    {'source': ['Lovers',     'Lovers'      ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Lovers',     'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Lovers',     'Hermit'      ], 'result': 'Justice'     },
    {'source': ['Lovers',     'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Lovers',     'Strength'    ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Death'       ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Temperance'  ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Devil'       ], 'result': 'Strength'    },
    {'source': ['Lovers',     'Tower'       ], 'result': 'Star'        },
    {'source': ['Lovers',     'Star'        ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Moon'        ], 'result': 'Empress'     },
    {'source': ['Lovers',     'Sun'         ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Aeon'        ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Fool'        ], 'result': 'Emperor'     },
    {'source': ['Chariot',    'Magician'    ], 'result': 'Devil'       },
    {'source': ['Chariot',    'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Empress'     ], 'result': 'Devil'       },
    {'source': ['Chariot',    'Emperor'     ], 'result': 'Hermit'      },
    {'source': ['Chariot',    'Hierophant'  ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Lovers'      ], 'result': 'Emperor'     },
    {'source': ['Chariot',    'Chariot'     ], 'result': 'Chariot'     },
    {'source': ['Chariot',    'Justice'     ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Hermit'      ], 'result': 'Temperance'  },
    {'source': ['Chariot',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Chariot',    'Strength'    ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Temperance'  ], 'result': 'Death'       },
    {'source': ['Chariot',    'Devil'       ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Aeon'        ], 'result': 'Death'       },
    {'source': ['Justice',    'Fool'        ], 'result': 'Lovers'      },
    {'source': ['Justice',    'Magician'    ], 'result': 'Hierophant'  },
    {'source': ['Justice',    'Priestess'   ], 'result': 'Lovers'      },
    {'source': ['Justice',    'Empress'     ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Emperor'     ], 'result': 'Devil'       },
    {'source': ['Justice',    'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Lovers'      ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Chariot'     ], 'result': 'Magician'    },
    {'source': ['Justice',    'Justice'     ], 'result': 'Justice'     },
    {'source': ['Justice',    'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Strength'    ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Hanged Man'  ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Justice',    'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Justice',    'Tower'       ], 'result': 'Star'        },
    {'source': ['Justice',    'Star'        ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Sun'         ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Hermit',     'Fool'        ], 'result': 'Priestess'   },
    {'source': ['Hermit',     'Magician'    ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Priestess'   ], 'result': 'Strength'    },
    {'source': ['Hermit',     'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Hermit',     'Emperor'     ], 'result': 'Strength'    },
    {'source': ['Hermit',     'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Lovers'      ], 'result': 'Justice'     },
    {'source': ['Hermit',     'Chariot'     ], 'result': 'Temperance'  },
    {'source': ['Hermit',     'Justice'     ], 'result': 'Priestess'   },
    {'source': ['Hermit',     'Hermit'      ], 'result': 'Hermit'      },
    {'source': ['Hermit',     'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hermit',     'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Star'        ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Moon'        ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Aeon'        ], 'result': 'Star'        },
    {'source': ['Fortune',    'Fool'        ], 'result': 'Justice'     },
    {'source': ['Fortune',    'Magician'    ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Fortune',    'Empress'     ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Hierophant'  ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Lovers'      ], 'result': 'Magician'    },
    {'source': ['Fortune',    'Chariot'     ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Hermit'      ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Fortune'     ], 'result': 'Fortune'     },
    {'source': ['Fortune',    'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Fortune',    'Devil'       ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Star'        ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Moon'        ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Fortune',    'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Strength',   'Fool'        ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Priestess'   ], 'result': 'Hermit'      },
    {'source': ['Strength',   'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Strength',   'Emperor'     ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Strength',   'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Strength',   'Justice'     ], 'result': 'Temperance'  },
    {'source': ['Strength',   'Hermit'      ], 'result': 'Fortune'     },
    {'source': ['Strength',   'Strength'    ], 'result': 'Strength'    },
    {'source': ['Strength',   'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Strength',   'Death'       ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Strength',   'Devil'       ], 'result': 'Fortune'     },
    {'source': ['Strength',   'Tower'       ], 'result': 'Devil'       },
    {'source': ['Strength',   'Star'        ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Moon'        ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Sun'         ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Judgment'    ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Fool'        ], 'result': 'Magician'    },
    {'source': ['Hanged Man', 'Magician'    ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Priestess'   ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Hanged Man', 'Emperor'     ], 'result': 'Hermit'      },
    {'source': ['Hanged Man', 'Hierophant'  ], 'result': 'Lovers'      },
    {'source': ['Hanged Man', 'Lovers'      ], 'result': 'Hermit'      },
    {'source': ['Hanged Man', 'Chariot'     ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Justice'     ], 'result': 'Priestess'   },
    {'source': ['Hanged Man', 'Hermit'      ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Strength'    ], 'result': 'Hermit'      },
    {'source': ['Hanged Man', 'Hanged Man'  ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Death'       ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Hanged Man', 'Devil'       ], 'result': 'Moon'        },
    {'source': ['Hanged Man', 'Tower'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Star'        ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Hanged Man', 'Aeon'        ], 'result': 'Temperance'  },
    {'source': ['Death',      'Fool'        ], 'result': 'Strength'    },
    {'source': ['Death',      'Priestess'   ], 'result': 'Emperor'     },
    {'source': ['Death',      'Empress'     ], 'result': 'Devil'       },
    {'source': ['Death',      'Emperor'     ], 'result': 'Moon'        },
    {'source': ['Death',      'Hierophant'  ], 'result': 'Empress'     },
    {'source': ['Death',      'Lovers'      ], 'result': 'Devil'       },
    {'source': ['Death',      'Justice'     ], 'result': 'Moon'        },
    {'source': ['Death',      'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Death',      'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Death',      'Death'       ], 'result': 'Death'       },
    {'source': ['Death',      'Moon'        ], 'result': 'Star'        },
    {'source': ['Temperance', 'Fool'        ], 'result': 'Hierophant'  },
    {'source': ['Temperance', 'Magician'    ], 'result': 'Death'       },
    {'source': ['Temperance', 'Priestess'   ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Temperance', 'Emperor'     ], 'result': 'Hanged Man'  },
    {'source': ['Temperance', 'Hierophant'  ], 'result': 'Strength'    },
    {'source': ['Temperance', 'Lovers'      ], 'result': 'Priestess'   },
    {'source': ['Temperance', 'Chariot'     ], 'result': 'Death'       },
    {'source': ['Temperance', 'Justice'     ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Temperance', 'Fortune'     ], 'result': 'Lovers'      },
    {'source': ['Temperance', 'Strength'    ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Hanged Man'  ], 'result': 'Hierophant'  },
    {'source': ['Temperance', 'Temperance'  ], 'result': 'Temperance'  },
    {'source': ['Temperance', 'Devil'       ], 'result': 'Death'       },
    {'source': ['Temperance', 'Tower'       ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Star'        ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Sun'         ], 'result': 'Star'        },
    {'source': ['Temperance', 'Judgment'    ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Aeon'        ], 'result': 'Star'        },
    {'source': ['Devil',      'Fool'        ], 'result': 'Hermit'      },
    {'source': ['Devil',      'Magician'    ], 'result': 'Temperance'  },
    {'source': ['Devil',      'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Devil',      'Lovers'      ], 'result': 'Strength'    },
    {'source': ['Devil',      'Chariot'     ], 'result': 'Hanged Man'  },
    {'source': ['Devil',      'Hermit'      ], 'result': 'Death'       },
    {'source': ['Devil',      'Fortune'     ], 'result': 'Moon'        },
    {'source': ['Devil',      'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Devil',      'Hanged Man'  ], 'result': 'Moon'        },
    {'source': ['Devil',      'Temperance'  ], 'result': 'Death'       },
    {'source': ['Devil',      'Devil'       ], 'result': 'Devil'       },
    {'source': ['Devil',      'Aeon'        ], 'result': 'Lovers'      },
    {'source': ['Tower',      'Fool'        ], 'result': 'Moon'        },
    {'source': ['Tower',      'Magician'    ], 'result': 'Empress'     },
    {'source': ['Tower',      'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Tower',      'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Tower',      'Lovers'      ], 'result': 'Star'        },
    {'source': ['Tower',      'Chariot'     ], 'result': 'Moon'        },
    {'source': ['Tower',      'Justice'     ], 'result': 'Star'        },
    {'source': ['Tower',      'Fortune'     ], 'result': 'Moon'        },
    {'source': ['Tower',      'Strength'    ], 'result': 'Devil'       },
    {'source': ['Tower',      'Hanged Man'  ], 'result': 'Death'       },
    {'source': ['Tower',      'Temperance'  ], 'result': 'Devil'       },
    {'source': ['Tower',      'Tower'       ], 'result': 'Tower'       },
    {'source': ['Tower',      'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Tower',      'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Star',       'Fool'        ], 'result': 'Aeon'        },
    {'source': ['Star',       'Magician'    ], 'result': 'Empress'     },
    {'source': ['Star',       'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Star',       'Empress'     ], 'result': 'Temperance'  },
    {'source': ['Star',       'Emperor'     ], 'result': 'Justice'     },
    {'source': ['Star',       'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Star',       'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Star',       'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Star',       'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Star',       'Fortune'     ], 'result': 'Moon'        },
    {'source': ['Star',       'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Star',       'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Star',       'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Star',       'Star'        ], 'result': 'Star'        },
    {'source': ['Star',       'Moon'        ], 'result': 'Death'       },
    {'source': ['Star',       'Sun'         ], 'result': 'Justice'     },
    {'source': ['Star',       'Judgment'    ], 'result': 'Temperance'  },
    {'source': ['Star',       'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Moon',       'Fool'        ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Magician'    ], 'result': 'Priestess'   },
    {'source': ['Moon',       'Priestess'   ], 'result': 'Star'        },
    {'source': ['Moon',       'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Moon',       'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Moon',       'Lovers'      ], 'result': 'Empress'     },
    {'source': ['Moon',       'Chariot'     ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Hermit'      ], 'result': 'Magician'    },
    {'source': ['Moon',       'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Moon',       'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Moon',       'Hanged Man'  ], 'result': 'Empress'     },
    {'source': ['Moon',       'Death'       ], 'result': 'Star'        },
    {'source': ['Moon',       'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Moon',       'Tower'       ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Star'        ], 'result': 'Death'       },
    {'source': ['Moon',       'Moon'        ], 'result': 'Moon'        },
    {'source': ['Moon',       'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Fool'        ], 'result': 'Empress'     },
    {'source': ['Sun',        'Magician'    ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Priestess'   ], 'result': 'Star'        },
    {'source': ['Sun',        'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Emperor'     ], 'result': 'Empress'     },
    {'source': ['Sun',        'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Sun',        'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Sun',        'Fortune'     ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Sun',        'Temperance'  ], 'result': 'Star'        },
    {'source': ['Sun',        'Star'        ], 'result': 'Justice'     },
    {'source': ['Sun',        'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Sun'         ], 'result': 'Sun'         },
    {'source': ['Sun',        'Judgment'    ], 'result': 'Star'        },
    {'source': ['Sun',        'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Judgment',   'Fool'        ], 'result': 'Star'        },
    {'source': ['Judgment',   'Priestess'   ], 'result': 'Empress'     },
    {'source': ['Judgment',   'Emperor'     ], 'result': 'Hierophant'  },
    {'source': ['Judgment',   'Hierophant'  ], 'result': 'Lovers'      },
    {'source': ['Judgment',   'Justice'     ], 'result': 'Aeon'        },
    {'source': ['Judgment',   'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Judgment',   'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Judgment',   'Tower'       ], 'result': 'Aeon'        },
    {'source': ['Judgment',   'Star'        ], 'result': 'Temperance'  },
    {'source': ['Judgment',   'Sun'         ], 'result': 'Star'        },
    {'source': ['Judgment',   'Judgment'    ], 'result': 'Judgment'    },
    {'source': ['Judgment',   'Aeon'        ], 'result': 'Star'        },
    {'source': ['Aeon',       'Fool'        ], 'result': 'Death'       },
    {'source': ['Aeon',       'Priestess'   ], 'result': 'Empress'     },
    {'source': ['Aeon',       'Empress'     ], 'result': 'Moon'        },
    {'source': ['Aeon',       'Lovers'      ], 'result': 'Hanged Man'  },
    {'source': ['Aeon',       'Chariot'     ], 'result': 'Death'       },
    {'source': ['Aeon',       'Hermit'      ], 'result': 'Star'        },
    {'source': ['Aeon',       'Fortune'     ], 'result': 'Devil'       },
    {'source': ['Aeon',       'Hanged Man'  ], 'result': 'Temperance'  },
    {'source': ['Aeon',       'Temperance'  ], 'result': 'Star'        },
    {'source': ['Aeon',       'Devil'       ], 'result': 'Lovers'      },
    {'source': ['Aeon',       'Tower'       ], 'result': 'Moon'        },
    {'source': ['Aeon',       'Star'        ], 'result': 'Devil'       },
    {'source': ['Aeon',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Aeon',       'Judgment'    ], 'result': 'Star'        },
    {'source': ['Aeon',       'Aeon'        ], 'result': 'Aeon'        },
    ];

const arcana3Combos = [
    {'source': ['Fool',       'Fool'        ], 'result': 'Fool'        },
    {'source': ['Fool',       'Magician'    ], 'result': 'Emperor'     },
    {'source': ['Fool',       'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Fool',       'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Fool',       'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Lovers'      ], 'result': 'Temperance'  },
    {'source': ['Fool',       'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Fool',       'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Fool',       'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Fortune'     ], 'result': 'Justice'     },
    {'source': ['Fool',       'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Fool',       'Hanged Man'  ], 'result': 'Magician'    },
    {'source': ['Fool',       'Death'       ], 'result': 'Strength'    },
    {'source': ['Fool',       'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Devil'       ], 'result': 'Justice'     },
    {'source': ['Fool',       'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fool',       'Star'        ], 'result': 'Aeon'        },
    {'source': ['Fool',       'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Fool',       'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fool',       'Aeon'        ], 'result': 'Death'       },
    {'source': ['Magician',   'Fool'        ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Magician'    ], 'result': 'Magician'    },
    {'source': ['Magician',   'Priestess'   ], 'result': 'Devil'       },
    {'source': ['Magician',   'Empress'     ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Magician',   'Lovers'      ], 'result': 'Devil'       },
    {'source': ['Magician',   'Chariot'     ], 'result': 'Moon'        },
    {'source': ['Magician',   'Justice'     ], 'result': 'Fool'        },
    {'source': ['Magician',   'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Strength'    ], 'result': 'Star'        },
    {'source': ['Magician',   'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Magician',   'Death'       ], 'result': 'Tower'       },
    {'source': ['Magician',   'Temperance'  ], 'result': 'Death'       },
    {'source': ['Magician',   'Devil'       ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Tower'       ], 'result': 'Empress'     },
    {'source': ['Magician',   'Star'        ], 'result': 'Empress'     },
    {'source': ['Magician',   'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Magician',   'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Magician',   'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Priestess',  'Fool'        ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Magician'    ], 'result': 'Devil'       },
    {'source': ['Priestess',  'Priestess'   ], 'result': 'Priestess'   },
    {'source': ['Priestess',  'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Emperor'     ], 'result': 'Hierophant'  },
    {'source': ['Priestess',  'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Lovers'      ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Justice'     ], 'result': 'Hierophant'  },
    {'source': ['Priestess',  'Hermit'      ], 'result': 'Fool'        },
    {'source': ['Priestess',  'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Death'       ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Devil'       ], 'result': 'Tower'       },
    {'source': ['Priestess',  'Tower'       ], 'result': 'Death'       },
    {'source': ['Priestess',  'Star'        ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Moon'        ], 'result': 'Star'        },
    {'source': ['Priestess',  'Sun'         ], 'result': 'Star'        },
    {'source': ['Priestess',  'Judgment'    ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Empress',    'Fool'        ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Magician'    ], 'result': 'Hanged Man'  },
    {'source': ['Empress',    'Priestess'   ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Empress'     ], 'result': 'Empress'     },
    {'source': ['Empress',    'Emperor'     ], 'result': 'Fool'        },
    {'source': ['Empress',    'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Lovers'      ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Empress',    'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Empress',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Empress',    'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Hanged Man'  ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Death'       ], 'result': 'Devil'       },
    {'source': ['Empress',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Devil'       ], 'result': 'Magician'    },
    {'source': ['Empress',    'Tower'       ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Star'        ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Moon'        ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Judgment'    ], 'result': 'Devil'       },
    {'source': ['Empress',    'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Fool'        ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Magician'    ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Priestess'   ], 'result': 'Hierophant'  },
    {'source': ['Emperor',    'Empress'     ], 'result': 'Fool'        },
    {'source': ['Emperor',    'Emperor'     ], 'result': 'Emperor'     },
    {'source': ['Emperor',    'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Lovers'      ], 'result': 'Strength'    },
    {'source': ['Emperor',    'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Fortune'     ], 'result': 'Sun'         },
    {'source': ['Emperor',    'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Hanged Man'  ], 'result': 'Temperance'  },
    {'source': ['Emperor',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Devil'       ], 'result': 'Tower'       },
    {'source': ['Emperor',    'Tower'       ], 'result': 'Death'       },
    {'source': ['Emperor',    'Star'        ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Moon'        ], 'result': 'Tower'       },
    {'source': ['Emperor',    'Sun'         ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Judgment'    ], 'result': 'Hierophant'  },
    {'source': ['Emperor',    'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Hierophant', 'Fool'        ], 'result': 'Hermit'      },
    {'source': ['Hierophant', 'Magician'    ], 'result': 'Hermit'      },
    {'source': ['Hierophant', 'Priestess'   ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Empress'     ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Hierophant'  ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Lovers'      ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Chariot'     ], 'result': 'Sun'         },
    {'source': ['Hierophant', 'Justice'     ], 'result': 'Magician'    },
    {'source': ['Hierophant', 'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Strength'    ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hierophant', 'Death'       ], 'result': 'Empress'     },
    {'source': ['Hierophant', 'Temperance'  ], 'result': 'Strength'    },
    {'source': ['Hierophant', 'Devil'       ], 'result': 'Fool'        },
    {'source': ['Hierophant', 'Tower'       ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Star'        ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Judgment'    ], 'result': 'Lovers'      },
    {'source': ['Hierophant', 'Aeon'        ], 'result': 'Tower'       },
    {'source': ['Lovers',     'Fool'        ], 'result': 'Temperance'  },
    {'source': ['Lovers',     'Magician'    ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Priestess'   ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Lovers',     'Emperor'     ], 'result': 'Strength'    },
    {'source': ['Lovers',     'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Lovers',     'Lovers'      ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Chariot'     ], 'result': 'Strength'    },
    {'source': ['Lovers',     'Justice'     ], 'result': 'Hanged Man'  },
    {'source': ['Lovers',     'Hermit'      ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Fortune'     ], 'result': 'Fool'        },
    {'source': ['Lovers',     'Strength'    ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Death'       ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Temperance'  ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Lovers',     'Tower'       ], 'result': 'Star'        },
    {'source': ['Lovers',     'Star'        ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Moon'        ], 'result': 'Empress'     },
    {'source': ['Lovers',     'Sun'         ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Judgment'    ], 'result': 'Sun'         },
    {'source': ['Lovers',     'Aeon'        ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Fool'        ], 'result': 'Devil'       },
    {'source': ['Chariot',    'Magician'    ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Priestess'   ], 'result': 'Emperor'     },
    {'source': ['Chariot',    'Empress'     ], 'result': 'Devil'       },
    {'source': ['Chariot',    'Emperor'     ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Hierophant'  ], 'result': 'Sun'         },
    {'source': ['Chariot',    'Lovers'      ], 'result': 'Strength'    },
    {'source': ['Chariot',    'Chariot'     ], 'result': 'Chariot'     },
    {'source': ['Chariot',    'Justice'     ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Fortune'     ], 'result': 'Hermit'      },
    {'source': ['Chariot',    'Strength'    ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Death'       ], 'result': 'Fool'        },
    {'source': ['Chariot',    'Temperance'  ], 'result': 'Death'       },
    {'source': ['Chariot',    'Devil'       ], 'result': 'Star'        },
    {'source': ['Chariot',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Star'        ], 'result': 'Sun'         },
    {'source': ['Chariot',    'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Sun'         ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Chariot',    'Aeon'        ], 'result': 'Death'       },
    {'source': ['Justice',    'Fool'        ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Magician'    ], 'result': 'Fool'        },
    {'source': ['Justice',    'Priestess'   ], 'result': 'Hierophant'  },
    {'source': ['Justice',    'Empress'     ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Hierophant'  ], 'result': 'Magician'    },
    {'source': ['Justice',    'Lovers'      ], 'result': 'Hanged Man'  },
    {'source': ['Justice',    'Chariot'     ], 'result': 'Magician'    },
    {'source': ['Justice',    'Justice'     ], 'result': 'Justice'     },
    {'source': ['Justice',    'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Justice',    'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Strength'    ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Hanged Man'  ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Justice',    'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Justice',    'Devil'       ], 'result': 'Tower'       },
    {'source': ['Justice',    'Tower'       ], 'result': 'Sun'         },
    {'source': ['Justice',    'Star'        ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Moon'        ], 'result': 'Tower'       },
    {'source': ['Justice',    'Sun'         ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Justice',    'Aeon'        ], 'result': 'Judgment'    },
    {'source': ['Hermit',     'Fool'        ], 'result': 'Priestess'   },
    {'source': ['Hermit',     'Magician'    ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Priestess'   ], 'result': 'Fool'        },
    {'source': ['Hermit',     'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Hermit',     'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Hermit',     'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Hermit',     'Chariot'     ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Justice'     ], 'result': 'Strength'    },
    {'source': ['Hermit',     'Hermit'      ], 'result': 'Hermit'      },
    {'source': ['Hermit',     'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hermit',     'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Death'       ], 'result': 'Tower'       },
    {'source': ['Hermit',     'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Tower'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Star'        ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Moon'        ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Sun'         ], 'result': 'Star'        },
    {'source': ['Hermit',     'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Hermit',     'Aeon'        ], 'result': 'Star'        },
    {'source': ['Fortune',    'Fool'        ], 'result': 'Justice'     },
    {'source': ['Fortune',    'Magician'    ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Fortune',    'Empress'     ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Emperor'     ], 'result': 'Sun'         },
    {'source': ['Fortune',    'Hierophant'  ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Lovers'      ], 'result': 'Fool'        },
    {'source': ['Fortune',    'Chariot'     ], 'result': 'Hermit'      },
    {'source': ['Fortune',    'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Hermit'      ], 'result': 'Emperor'     },
    {'source': ['Fortune',    'Fortune'     ], 'result': 'Fortune'     },
    {'source': ['Fortune',    'Strength'    ], 'result': 'Sun'         },
    {'source': ['Fortune',    'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Death'       ], 'result': 'Judgment'    },
    {'source': ['Fortune',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Fortune',    'Devil'       ], 'result': 'Hermit'      },
    {'source': ['Fortune',    'Tower'       ], 'result': 'Aeon'        },
    {'source': ['Fortune',    'Star'        ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Moon'        ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Fortune',    'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fortune',    'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Strength',   'Fool'        ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Magician'    ], 'result': 'Star'        },
    {'source': ['Strength',   'Priestess'   ], 'result': 'Chariot'     },
    {'source': ['Strength',   'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Strength',   'Emperor'     ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Hierophant'  ], 'result': 'Emperor'     },
    {'source': ['Strength',   'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Strength',   'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Strength',   'Justice'     ], 'result': 'Temperance'  },
    {'source': ['Strength',   'Hermit'      ], 'result': 'Emperor'     },
    {'source': ['Strength',   'Fortune'     ], 'result': 'Sun'         },
    {'source': ['Strength',   'Strength'    ], 'result': 'Strength'    },
    {'source': ['Strength',   'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Strength',   'Death'       ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Strength',   'Devil'       ], 'result': 'Empress'     },
    {'source': ['Strength',   'Tower'       ], 'result': 'Judgment'    },
    {'source': ['Strength',   'Star'        ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Moon'        ], 'result': 'Aeon'        },
    {'source': ['Strength',   'Sun'         ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Judgment'    ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Aeon'        ], 'result': 'Tower'       },
    {'source': ['Hanged Man', 'Fool'        ], 'result': 'Magician'    },
    {'source': ['Hanged Man', 'Magician'    ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Priestess'   ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Hanged Man', 'Emperor'     ], 'result': 'Temperance'  },
    {'source': ['Hanged Man', 'Hierophant'  ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Lovers'      ], 'result': 'Hermit'      },
    {'source': ['Hanged Man', 'Chariot'     ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Justice'     ], 'result': 'Priestess'   },
    {'source': ['Hanged Man', 'Hermit'      ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Hanged Man', 'Hanged Man'  ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Death'       ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Hanged Man', 'Devil'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Tower'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Star'        ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Hanged Man', 'Sun'         ], 'result': 'Judgment'    },
    {'source': ['Hanged Man', 'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Hanged Man', 'Aeon'        ], 'result': 'Temperance'  },
    {'source': ['Death',      'Fool'        ], 'result': 'Strength'    },
    {'source': ['Death',      'Magician'    ], 'result': 'Tower'       },
    {'source': ['Death',      'Priestess'   ], 'result': 'Emperor'     },
    {'source': ['Death',      'Empress'     ], 'result': 'Devil'       },
    {'source': ['Death',      'Emperor'     ], 'result': 'Moon'        },
    {'source': ['Death',      'Hierophant'  ], 'result': 'Empress'     },
    {'source': ['Death',      'Lovers'      ], 'result': 'Devil'       },
    {'source': ['Death',      'Chariot'     ], 'result': 'Judgment'    },
    {'source': ['Death',      'Justice'     ], 'result': 'Moon'        },
    {'source': ['Death',      'Hermit'      ], 'result': 'Tower'       },
    {'source': ['Death',      'Fortune'     ], 'result': 'Judgment'    },
    {'source': ['Death',      'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Death',      'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Death',      'Death'       ], 'result': 'Death'       },
    {'source': ['Death',      'Temperance'  ], 'result': 'Tower'       },
    {'source': ['Death',      'Devil'       ], 'result': 'Judgment'    },
    {'source': ['Death',      'Tower'       ], 'result': 'Sun'         },
    {'source': ['Death',      'Star'        ], 'result': 'Tower'       },
    {'source': ['Death',      'Moon'        ], 'result': 'Star'        },
    {'source': ['Death',      'Sun'         ], 'result': 'Moon'        },
    {'source': ['Death',      'Judgment'    ], 'result': 'Fool'        },
    {'source': ['Death',      'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Temperance', 'Fool'        ], 'result': 'Hierophant'  },
    {'source': ['Temperance', 'Magician'    ], 'result': 'Death'       },
    {'source': ['Temperance', 'Priestess'   ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Temperance', 'Emperor'     ], 'result': 'Hanged Man'  },
    {'source': ['Temperance', 'Hierophant'  ], 'result': 'Strength'    },
    {'source': ['Temperance', 'Lovers'      ], 'result': 'Priestess'   },
    {'source': ['Temperance', 'Chariot'     ], 'result': 'Death'       },
    {'source': ['Temperance', 'Justice'     ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Temperance', 'Fortune'     ], 'result': 'Lovers'      },
    {'source': ['Temperance', 'Strength'    ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Hanged Man'  ], 'result': 'Hierophant'  },
    {'source': ['Temperance', 'Death'       ], 'result': 'Tower'       },
    {'source': ['Temperance', 'Temperance'  ], 'result': 'Temperance'  },
    {'source': ['Temperance', 'Devil'       ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Tower'       ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Star'        ], 'result': 'Hermit'      },
    {'source': ['Temperance', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Sun'         ], 'result': 'Judgment'    },
    {'source': ['Temperance', 'Judgment'    ], 'result': 'Justice'     },
    {'source': ['Temperance', 'Aeon'        ], 'result': 'Star'        },
    {'source': ['Devil',      'Fool'        ], 'result': 'Justice'     },
    {'source': ['Devil',      'Magician'    ], 'result': 'Temperance'  },
    {'source': ['Devil',      'Priestess'   ], 'result': 'Tower'       },
    {'source': ['Devil',      'Empress'     ], 'result': 'Magician'    },
    {'source': ['Devil',      'Emperor'     ], 'result': 'Tower'       },
    {'source': ['Devil',      'Hierophant'  ], 'result': 'Fool'        },
    {'source': ['Devil',      'Lovers'      ], 'result': 'Death'       },
    {'source': ['Devil',      'Chariot'     ], 'result': 'Star'        },
    {'source': ['Devil',      'Justice'     ], 'result': 'Tower'       },
    {'source': ['Devil',      'Hermit'      ], 'result': 'Death'       },
    {'source': ['Devil',      'Fortune'     ], 'result': 'Hermit'      },
    {'source': ['Devil',      'Strength'    ], 'result': 'Empress'     },
    {'source': ['Devil',      'Hanged Man'  ], 'result': 'Death'       },
    {'source': ['Devil',      'Death'       ], 'result': 'Judgment'    },
    {'source': ['Devil',      'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Devil',      'Devil'       ], 'result': 'Devil'       },
    {'source': ['Devil',      'Tower'       ], 'result': 'Judgment'    },
    {'source': ['Devil',      'Star'        ], 'result': 'Magician'    },
    {'source': ['Devil',      'Moon'        ], 'result': 'Judgment'    },
    {'source': ['Devil',      'Sun'         ], 'result': 'Death'       },
    {'source': ['Devil',      'Judgment'    ], 'result': 'Moon'        },
    {'source': ['Devil',      'Aeon'        ], 'result': 'Lovers'      },
    {'source': ['Tower',      'Fool'        ], 'result': 'Moon'        },
    {'source': ['Tower',      'Magician'    ], 'result': 'Empress'     },
    {'source': ['Tower',      'Priestess'   ], 'result': 'Death'       },
    {'source': ['Tower',      'Empress'     ], 'result': 'Chariot'     },
    {'source': ['Tower',      'Emperor'     ], 'result': 'Death'       },
    {'source': ['Tower',      'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Tower',      'Lovers'      ], 'result': 'Star'        },
    {'source': ['Tower',      'Chariot'     ], 'result': 'Moon'        },
    {'source': ['Tower',      'Justice'     ], 'result': 'Sun'         },
    {'source': ['Tower',      'Hermit'      ], 'result': 'Death'       },
    {'source': ['Tower',      'Fortune'     ], 'result': 'Aeon'        },
    {'source': ['Tower',      'Strength'    ], 'result': 'Judgment'    },
    {'source': ['Tower',      'Hanged Man'  ], 'result': 'Death'       },
    {'source': ['Tower',      'Death'       ], 'result': 'Sun'         },
    {'source': ['Tower',      'Temperance'  ], 'result': 'Devil'       },
    {'source': ['Tower',      'Devil'       ], 'result': 'Judgment'    },
    {'source': ['Tower',      'Tower'       ], 'result': 'Tower'       },
    {'source': ['Tower',      'Star'        ], 'result': 'Judgment'    },
    {'source': ['Tower',      'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Sun'         ], 'result': 'Moon'        },
    {'source': ['Tower',      'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Tower',      'Aeon'        ], 'result': 'Fool'        },
    {'source': ['Star',       'Fool'        ], 'result': 'Aeon'        },
    {'source': ['Star',       'Magician'    ], 'result': 'Empress'     },
    {'source': ['Star',       'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Star',       'Empress'     ], 'result': 'Temperance'  },
    {'source': ['Star',       'Emperor'     ], 'result': 'Hermit'      },
    {'source': ['Star',       'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Star',       'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Star',       'Chariot'     ], 'result': 'Sun'         },
    {'source': ['Star',       'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Star',       'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Star',       'Fortune'     ], 'result': 'Moon'        },
    {'source': ['Star',       'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Star',       'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Star',       'Death'       ], 'result': 'Tower'       },
    {'source': ['Star',       'Temperance'  ], 'result': 'Hermit'      },
    {'source': ['Star',       'Devil'       ], 'result': 'Magician'    },
    {'source': ['Star',       'Tower'       ], 'result': 'Judgment'    },
    {'source': ['Star',       'Star'        ], 'result': 'Star'        },
    {'source': ['Star',       'Moon'        ], 'result': 'Sun'         },
    {'source': ['Star',       'Sun'         ], 'result': 'Aeon'        },
    {'source': ['Star',       'Judgment'    ], 'result': 'Temperance'  },
    {'source': ['Star',       'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Moon',       'Fool'        ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Magician'    ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Priestess'   ], 'result': 'Star'        },
    {'source': ['Moon',       'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Moon',       'Emperor'     ], 'result': 'Tower'       },
    {'source': ['Moon',       'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Moon',       'Lovers'      ], 'result': 'Empress'     },
    {'source': ['Moon',       'Chariot'     ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Justice'     ], 'result': 'Tower'       },
    {'source': ['Moon',       'Hermit'      ], 'result': 'Magician'    },
    {'source': ['Moon',       'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Moon',       'Strength'    ], 'result': 'Aeon'        },
    {'source': ['Moon',       'Hanged Man'  ], 'result': 'Empress'     },
    {'source': ['Moon',       'Death'       ], 'result': 'Star'        },
    {'source': ['Moon',       'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Moon',       'Devil'       ], 'result': 'Judgment'    },
    {'source': ['Moon',       'Tower'       ], 'result': 'Fortune'     },
    {'source': ['Moon',       'Star'        ], 'result': 'Sun'         },
    {'source': ['Moon',       'Moon'        ], 'result': 'Moon'        },
    {'source': ['Moon',       'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Moon',       'Judgment'    ], 'result': 'Priestess'   },
    {'source': ['Moon',       'Aeon'        ], 'result': 'Judgment'    },
    {'source': ['Sun',        'Fool'        ], 'result': 'Empress'     },
    {'source': ['Sun',        'Magician'    ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Priestess'   ], 'result': 'Star'        },
    {'source': ['Sun',        'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Sun',        'Emperor'     ], 'result': 'Empress'     },
    {'source': ['Sun',        'Hierophant'  ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Lovers'      ], 'result': 'Hierophant'  },
    {'source': ['Sun',        'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Sun',        'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Sun',        'Hermit'      ], 'result': 'Star'        },
    {'source': ['Sun',        'Fortune'     ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Sun',        'Hanged Man'  ], 'result': 'Judgment'    },
    {'source': ['Sun',        'Death'       ], 'result': 'Moon'        },
    {'source': ['Sun',        'Temperance'  ], 'result': 'Judgment'    },
    {'source': ['Sun',        'Devil'       ], 'result': 'Death'       },
    {'source': ['Sun',        'Tower'       ], 'result': 'Moon'        },
    {'source': ['Sun',        'Star'        ], 'result': 'Aeon'        },
    {'source': ['Sun',        'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Sun'         ], 'result': 'Sun'         },
    {'source': ['Sun',        'Judgment'    ], 'result': 'Star'        },
    {'source': ['Sun',        'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Judgment',   'Fool'        ], 'result': 'Star'        },
    {'source': ['Judgment',   'Magician'    ], 'result': 'Tower'       },
    {'source': ['Judgment',   'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Judgment',   'Empress'     ], 'result': 'Devil'       },
    {'source': ['Judgment',   'Emperor'     ], 'result': 'Hierophant'  },
    {'source': ['Judgment',   'Hierophant'  ], 'result': 'Lovers'      },
    {'source': ['Judgment',   'Lovers'      ], 'result': 'Sun'         },
    {'source': ['Judgment',   'Chariot'     ], 'result': 'Tower'       },
    {'source': ['Judgment',   'Justice'     ], 'result': 'Aeon'        },
    {'source': ['Judgment',   'Hermit'      ], 'result': 'Tower'       },
    {'source': ['Judgment',   'Fortune'     ], 'result': 'Star'        },
    {'source': ['Judgment',   'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Judgment',   'Hanged Man'  ], 'result': 'Aeon'        },
    {'source': ['Judgment',   'Death'       ], 'result': 'Fool'        },
    {'source': ['Judgment',   'Temperance'  ], 'result': 'Justice'     },
    {'source': ['Judgment',   'Devil'       ], 'result': 'Moon'        },
    {'source': ['Judgment',   'Tower'       ], 'result': 'Aeon'        },
    {'source': ['Judgment',   'Star'        ], 'result': 'Temperance'  },
    {'source': ['Judgment',   'Moon'        ], 'result': 'Priestess'   },
    {'source': ['Judgment',   'Sun'         ], 'result': 'Star'        },
    {'source': ['Judgment',   'Judgment'    ], 'result': 'Judgment'    },
    {'source': ['Judgment',   'Aeon'        ], 'result': 'Fool'        },
    {'source': ['Aeon',       'Fool'        ], 'result': 'Death'       },
    {'source': ['Aeon',       'Magician'    ], 'result': 'Sun'         },
    {'source': ['Aeon',       'Priestess'   ], 'result': 'Empress'     },
    {'source': ['Aeon',       'Empress'     ], 'result': 'Moon'        },
    {'source': ['Aeon',       'Emperor'     ], 'result': 'Sun'         },
    {'source': ['Aeon',       'Hierophant'  ], 'result': 'Tower'       },
    {'source': ['Aeon',       'Lovers'      ], 'result': 'Hanged Man'  },
    {'source': ['Aeon',       'Chariot'     ], 'result': 'Death'       },
    {'source': ['Aeon',       'Justice'     ], 'result': 'Judgment'    },
    {'source': ['Aeon',       'Hermit'      ], 'result': 'Star'        },
    {'source': ['Aeon',       'Fortune'     ], 'result': 'Devil'       },
    {'source': ['Aeon',       'Strength'    ], 'result': 'Tower'       },
    {'source': ['Aeon',       'Hanged Man'  ], 'result': 'Temperance'  },
    {'source': ['Aeon',       'Death'       ], 'result': 'Sun'         },
    {'source': ['Aeon',       'Temperance'  ], 'result': 'Star'        },
    {'source': ['Aeon',       'Devil'       ], 'result': 'Lovers'      },
    {'source': ['Aeon',       'Tower'       ], 'result': 'Fool'        },
    {'source': ['Aeon',       'Star'        ], 'result': 'Devil'       },
    {'source': ['Aeon',       'Moon'        ], 'result': 'Judgment'    },
    {'source': ['Aeon',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Aeon',       'Judgment'    ], 'result': 'Fool'        },
    {'source': ['Aeon',       'Aeon'        ], 'result': 'Aeon'        },
    ];
